package safeslop

// Generated by WriteCatalog; specs/0059 D1 requires catalog.cue and catalog.json
// to be re-emitted together so mutation artifacts never drift.
catalog: {
	bundles: [{
		description: "everyday CLI ergonomics: ripgrep, fd, bat, eza, fzf, zoxide"
		name:        "base-tools"
		packages: ["ripgrep", "fd", "bat", "eza", "fzf", "zoxide"]
	}, {
		description: "Claude Code (Anthropic) + Node runtime"
		name:        "claude"
		packages: ["node", "claude-code"]
	}, {
		description: "Go toolchain (compiler + module proxy egress)"
		name:        "go"
		packages: ["go"]
	}, {
		description: "Node.js + pnpm + bun for JS/TS work"
		name:        "node"
		packages: ["node", "pnpm", "bun"]
	}, {
		description: "daily-driver multi-language set: CLI ergonomics + Node/Python/Go/Rust toolchains"
		name:        "personal"
		packages: ["ripgrep", "fd", "bat", "eza", "fzf", "zoxide", "yq", "node", "pnpm", "python3", "uv", "ruff", "go", "rust", "hyperfine", "tokei", "sccache"]
	}, {
		description: "pi coding agent + Node runtime"
		name:        "pi"
		packages: ["node", "pi"]
	}, {
		description: "Python 3 + uv + ruff (linter/formatter)"
		name:        "python"
		packages: ["python3", "uv", "ruff"]
	}, {
		description: "Rust toolchain + common cargo subcommands"
		name:        "rust"
		packages: ["rust", "cargo-nextest", "cargo-audit", "cargo-deny", "cargo-expand", "cargo-make", "cargo-watch", "sccache"]
	}, {
		description: "Rust for no_std / embedded targets (cargo-binutils, flip-link)"
		name:        "rust-embedded"
		packages: ["rust", "cargo-binutils", "flip-link"]
	}, {
		description: "JS/TS web development: TypeScript, Vite, ESLint, Prettier, web-ext"
		name:        "web"
		packages: ["node", "pnpm", "typescript", "vite", "eslint", "prettier", "web-ext"]
	}]
	defaults: {
		claude: "claude"
		pi:     "pi"
	}
	packages: [{
		buildFetch: ["github.com"]
		kind: "binary"
		name: "bat"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/bat/releases"
		}
		version: "0.25.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "bun"
		note: "provides bunx"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-x64.zip"
				arm64: "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-aarch64.zip"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/oven-sh/bun/releases"
		}
		version: "1.1.38"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-audit"
		note: "cargo-* subcommands all require the rust toolchain; their closure pulls rust in"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/rustsec/rustsec/releases"
		}
		version: "0.21.2"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-binutils"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/rust-embedded/cargo-binutils/releases"
		}
		version: "0.3.6"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-deny"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/EmbarkStudios/cargo-deny/releases"
		}
		version: "0.18.2"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-expand"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/dtolnay/cargo-expand/releases"
		}
		version: "1.0.110"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-make"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/sagiegurari/cargo-make/releases"
		}
		version: "0.37.26"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-nextest"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/nextest-rs/nextest/releases"
		}
		version: "0.9.98"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-watch"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/watchexec/cargo-watch/releases"
		}
		version: "8.5.4"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "claude-code"
		note: "runtime egress scoped to Anthropic API"
		requires: ["node"]
		runtimeEgress: [".anthropic.com"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/@anthropic-ai%2fclaude-code"
		}
		version: "2.1.121"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "eslint"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/eslint"
		}
		version: "9.22.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "eza"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/eza-community/eza/releases/download/v{version}/eza_x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/eza-community/eza/releases/download/v{version}/eza_aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/eza-community/eza/releases"
		}
		version: "0.21.1"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "fd"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/fd/releases"
		}
		version: "10.2.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "flip-link"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/knurling-rs/flip-link/releases"
		}
		version: "0.1.12"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "fzf"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/junegunn/fzf/releases/download/v{version}/fzf-{version}-linux_amd64.tar.gz"
				arm64: "https://github.com/junegunn/fzf/releases/download/v{version}/fzf-{version}-linux_arm64.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/junegunn/fzf/releases"
		}
		version: "0.59.0"
	}, {
		buildFetch: ["go.dev"]
		kind: "binary"
		name: "go"
		note: "the Go toolchain; go get/go build fetch modules via the module proxy + checksum DB (scoped exact hosts)"
		runtimeEgress: ["proxy.golang.org", "sum.golang.org"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://go.dev/dl/go{version}.linux-amd64.tar.gz"
				arm64: "https://go.dev/dl/go{version}.linux-arm64.tar.gz"
			}
			kind:        "url-regex"
			manifestURL: "https://go.dev/dl/?mode=json&include=all"
			url:         "https://go.dev/dl/?mode=json&include=all"
		}
		version: "1.26.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "hyperfine"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/hyperfine/releases/download/v{version}/hyperfine-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/hyperfine/releases/download/v{version}/hyperfine-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/hyperfine/releases"
		}
		version: "1.19.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "mise"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/jdx/mise/releases/download/v{version}/mise-v{version}-linux-x64.tar.gz"
				arm64: "https://github.com/jdx/mise/releases/download/v{version}/mise-v{version}-linux-arm64.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/jdx/mise/releases"
		}
		version: "2026.6.11"
	}, {
		buildFetch: ["nodejs.org"]
		kind: "binary"
		name: "node"
		note: "official multi-arch tarball, sha256-verified per arch (digests from nodejs.org/dist/vX/SHASUMS256.txt; amd64 == the x64 tarball). Provides npm, which claude-code/pi/pnpm and the JS/TS dev tools require"
		sha256: {
			amd64: "9749e988f437343b7fa832c69ded82a312e41a03116d766797ac14f6f9eee578"
			arm64: "0294e8b915ab75f92c7513d2fcb830ae06e10684e6c603e99a87dbf8835389c1"
		}
		upstream: {
			asset: {
				amd64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-x64.tar.xz"
				arm64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-arm64.tar.xz"
			}
			kind:        "node-dist"
			manifestURL: "https://nodejs.org/dist/v{version}/SHASUMS256.txt"
			url:         "https://nodejs.org/dist/index.json"
		}
		version: "22.23.1"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "pi"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/@earendil-works%2fpi-coding-agent"
		}
		version: "0.80.2"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "pnpm"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/pnpm"
		}
		version: "9.15.0"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "prettier"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/prettier"
		}
		version: "3.5.3"
	}, {
		buildFetch: ["deb.debian.org", "snapshot.debian.org"]
		kind: "apt"
		name: "python3"
		note: "apt kind — transitives are frozen by the golden-base Debian-snapshot pin (specs/0058 N2.2); reserved for what only apt provides"
		upstream: {
			kind: "debian-snapshot"
			url:  "https://snapshot.debian.org/mr/package/python3.11/"
		}
		version: "3.11"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "ripgrep"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/BurntSushi/ripgrep/releases/download/{version}/ripgrep-{version}-x86_64-unknown-linux-musl.tar.gz"
				arm64: "https://github.com/BurntSushi/ripgrep/releases/download/{version}/ripgrep-{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/BurntSushi/ripgrep/releases"
		}
		version: "14.1.1"
	}, {
		buildFetch: ["astral.sh", "github.com"]
		kind: "binary"
		name: "ruff"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/astral-sh/ruff/releases/download/{version}/ruff-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/astral-sh/ruff/releases/download/{version}/ruff-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/astral-sh/ruff/releases"
		}
		version: "0.11.0"
	}, {
		buildFetch: ["static.rust-lang.org"]
		kind: "binary"
		name: "rust"
		note: "the rustc+cargo toolchain tarball; cargo fetches crates + the sparse index from *.crates.io and toolchain artifacts from static.rust-lang.org (leading dot covers index/static)"
		runtimeEgress: [".crates.io", "static.rust-lang.org"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://static.rust-lang.org/dist/rust-{version}-x86_64-unknown-linux-gnu.tar.xz"
				arm64: "https://static.rust-lang.org/dist/rust-{version}-aarch64-unknown-linux-gnu.tar.xz"
			}
			kind:        "url-regex"
			manifestURL: "https://static.rust-lang.org/dist/channel-rust-stable.toml"
			url:         "https://static.rust-lang.org/dist/channel-rust-stable.toml"
		}
		version: "1.96.0"
	}, {
		buildFetch: ["static.rust-lang.org"]
		kind: "binary"
		name: "rustup"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://static.rust-lang.org/rustup/archive/{version}/x86_64-unknown-linux-gnu/rustup-init"
				arm64: "https://static.rust-lang.org/rustup/archive/{version}/aarch64-unknown-linux-gnu/rustup-init"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/rust-lang/rustup/releases"
		}
		version: "1.28.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "sccache"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/mozilla/sccache/releases"
		}
		version: "0.10.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "tokei"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/XAMPPRocky/tokei/releases"
		}
		version: "13.0.0"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "typescript"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/typescript"
		}
		version: "5.8.2"
	}, {
		buildFetch: ["astral.sh", "github.com"]
		kind: "binary"
		name: "uv"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/astral-sh/uv/releases/download/{version}/uv-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/astral-sh/uv/releases/download/{version}/uv-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/astral-sh/uv/releases"
		}
		version: "0.5.11"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "vite"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/vite"
		}
		version: "6.3.5"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "web-ext"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/web-ext"
		}
		version: "8.5.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "yq"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/mikefarah/yq/releases/download/v{version}/yq_linux_amd64"
				arm64: "https://github.com/mikefarah/yq/releases/download/v{version}/yq_linux_arm64"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/mikefarah/yq/releases"
		}
		version: "4.45.4"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "zoxide"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/ajeetdsouza/zoxide/releases/download/v{version}/zoxide-{version}-x86_64-unknown-linux-musl.tar.gz"
				arm64: "https://github.com/ajeetdsouza/zoxide/releases/download/v{version}/zoxide-{version}-aarch64-unknown-linux-musl.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/ajeetdsouza/zoxide/releases"
		}
		version: "0.9.8"
	}]
}
