package safeslop

// Generated by WriteCatalog; specs/0059 D1 requires catalog.cue and catalog.json
// to be re-emitted together so mutation artifacts never drift.
catalog: {
	bundles: [{
		description: "everyday CLI ergonomics: ripgrep, fd, bat, eza, fzf, zoxide"
		name:        "base-tools"
		packages: ["ripgrep", "fd", "bat", "eza", "fzf", "zoxide"]
	}, {
		description: "Claude Code (Anthropic) + Node runtime"
		name:        "claude"
		packages: ["node", "claude-code"]
	}, {
		description: "Go toolchain (compiler + module proxy egress)"
		name:        "go"
		packages: ["go"]
	}, {
		description: "Node.js + pnpm + bun for JS/TS work"
		name:        "node"
		packages: ["node", "pnpm", "bun"]
	}, {
		description: "daily-driver multi-language set: CLI ergonomics + Node/Python/Go/Rust toolchains"
		name:        "personal"
		packages: ["ripgrep", "fd", "bat", "eza", "fzf", "zoxide", "yq", "node", "pnpm", "python3", "uv", "ruff", "go", "rust", "hyperfine", "tokei", "sccache"]
	}, {
		description: "pi coding agent + Node runtime"
		name:        "pi"
		packages: ["node", "pi"]
	}, {
		description: "Python 3 + uv + ruff (linter/formatter)"
		name:        "python"
		packages: ["python3", "uv", "ruff"]
	}, {
		description: "Rust toolchain + common cargo subcommands"
		name:        "rust"
		packages: ["rust", "cargo-nextest", "cargo-audit", "cargo-deny", "cargo-expand", "cargo-make", "cargo-watch", "sccache"]
	}, {
		description: "Rust for no_std / embedded targets (cargo-binutils, flip-link)"
		name:        "rust-embedded"
		packages: ["rust", "cargo-binutils", "flip-link"]
	}, {
		description: "JS/TS web development: TypeScript, Vite, ESLint, Prettier, web-ext"
		name:        "web"
		packages: ["node", "pnpm", "typescript", "vite", "eslint", "prettier", "web-ext"]
	}]
	defaults: {
		claude: "claude"
		pi:     "pi"
	}
	packages: [{
		buildFetch: ["github.com"]
		kind: "binary"
		name: "bat"
		sha256: {
			amd64: "31bbbcc0d9f5abe16399425c98ffbf21aaa0ce190c7b75d4f32297696ff32b81"
			arm64: "d155df218dc2d662da191e2dacddc71c90197b62ebe7e2923a659e5dd055d5cb"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/bat/releases"
		}
		version: "0.25.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "bun"
		note: "provides bunx"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-x64.zip"
				arm64: "https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-linux-aarch64.zip"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/oven-sh/bun/releases"
		}
		version: "1.1.38"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-audit"
		note: "cargo-* subcommands all require the rust toolchain; their closure pulls rust in"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/rustsec/rustsec/releases"
		}
		version: "0.21.2"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-binutils"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/rust-embedded/cargo-binutils/releases"
		}
		version: "0.3.6"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-deny"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/EmbarkStudios/cargo-deny/releases"
		}
		version: "0.18.2"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-expand"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/dtolnay/cargo-expand/releases"
		}
		version: "1.0.110"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-make"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/sagiegurari/cargo-make/releases"
		}
		version: "0.37.26"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-nextest"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/nextest-rs/nextest/releases"
		}
		version: "0.9.98"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "cargo-watch"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/watchexec/cargo-watch/releases"
		}
		version: "8.5.4"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "claude-code"
		note: "runtime egress scoped to Anthropic API"
		requires: ["node"]
		runtimeEgress: [".anthropic.com"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/@anthropic-ai%2fclaude-code"
		}
		version: "2.1.121"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "eslint"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/eslint"
		}
		version: "9.22.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "eza"
		sha256: {
			amd64: "3c2baacd598598da744a3996d8b6a37caa330e43c1a989026ccf9a9542731434"
			arm64: "88debe2b2f8454b45c6d4b12ba32b5192fd345de0fdc31c6e543ef12daea8870"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/eza-community/eza/releases/download/v{version}/eza_x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/eza-community/eza/releases/download/v{version}/eza_aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/eza-community/eza/releases"
		}
		version: "0.21.1"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "fd"
		sha256: {
			amd64: "5f9030bcb0e1d03818521ed2e3d74fdb046480a45a4418ccff4f070241b4ed25"
			arm64: "6de8be7a3d8ca27954a6d1e22bc327af4cf6fc7622791e68b820197f915c422b"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/fd/releases"
		}
		version: "10.2.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "flip-link"
		requires: ["rust"]
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			kind: "github-releases"
			url:  "https://api.github.com/repos/knurling-rs/flip-link/releases"
		}
		version: "0.1.12"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "fzf"
		sha256: {
			amd64: "4957db97bb8d3af947745d8f0309572bd7867666de30367e9422d55761ad076a"
			arm64: "496fe77565d9008a684fff6ca9f23a48b41e674e8134e5f6cddee8e2cad129a9"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/junegunn/fzf/releases/download/v{version}/fzf-{version}-linux_amd64.tar.gz"
				arm64: "https://github.com/junegunn/fzf/releases/download/v{version}/fzf-{version}-linux_arm64.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/junegunn/fzf/releases"
		}
		version: "0.59.0"
	}, {
		buildFetch: ["go.dev"]
		kind: "binary"
		name: "go"
		note: "the Go toolchain; go get/go build fetch modules via the module proxy + checksum DB (scoped exact hosts)"
		runtimeEgress: ["proxy.golang.org", "sum.golang.org"]
		sha256: {
			amd64: "aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235"
			arm64: "bd03b743eb6eb4193ea3c3fd3956546bf0e3ca5b7076c8226334afe6b75704cd"
		}
		upstream: {
			asset: {
				amd64: "https://go.dev/dl/go{version}.linux-amd64.tar.gz"
				arm64: "https://go.dev/dl/go{version}.linux-arm64.tar.gz"
			}
			kind:        "url-regex"
			manifestURL: "https://go.dev/dl/?mode=json&include=all"
			url:         "https://go.dev/dl/?mode=json&include=all"
		}
		version: "1.26.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "hyperfine"
		sha256: {
			amd64: "d5550bbdc240d2aaa8f43ea2dc8b03a306afb30ea8464cd8b2faa9486ed1019e"
			arm64: "7f9c0522e1acf869e0558e085c43f2cea3e30e4f7a4b7bc3d5540cbdee7b4273"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/sharkdp/hyperfine/releases/download/v{version}/hyperfine-v{version}-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/sharkdp/hyperfine/releases/download/v{version}/hyperfine-v{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/sharkdp/hyperfine/releases"
		}
		version: "1.19.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "mise"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/jdx/mise/releases/download/v{version}/mise-v{version}-linux-x64.tar.gz"
				arm64: "https://github.com/jdx/mise/releases/download/v{version}/mise-v{version}-linux-arm64.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/jdx/mise/releases"
		}
		version: "2026.6.11"
	}, {
		buildFetch: ["nodejs.org"]
		kind: "binary"
		name: "node"
		note: "official multi-arch tarball, sha256-verified per arch (digests from nodejs.org/dist/vX/SHASUMS256.txt; amd64 == the x64 tarball). Provides npm, which claude-code/pi/pnpm and the JS/TS dev tools require"
		sha256: {
			amd64: "9749e988f437343b7fa832c69ded82a312e41a03116d766797ac14f6f9eee578"
			arm64: "0294e8b915ab75f92c7513d2fcb830ae06e10684e6c603e99a87dbf8835389c1"
		}
		upstream: {
			asset: {
				amd64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-x64.tar.xz"
				arm64: "https://nodejs.org/dist/v{version}/node-v{version}-linux-arm64.tar.xz"
			}
			kind:        "node-dist"
			manifestURL: "https://nodejs.org/dist/v{version}/SHASUMS256.txt"
			url:         "https://nodejs.org/dist/index.json"
		}
		version: "22.23.1"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "pi"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/@earendil-works%2fpi-coding-agent"
		}
		version: "0.80.7"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "pnpm"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/pnpm"
		}
		version: "9.15.0"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "prettier"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/prettier"
		}
		version: "3.5.3"
	}, {
		buildFetch: ["deb.debian.org", "snapshot.debian.org"]
		kind: "apt"
		name: "python3"
		note: "apt leaf 3.11.2-1+b1 and its transitives are frozen by the golden-base Debian snapshot 20260628T204121Z (specs/0058 N2.2)"
		upstream: {
			kind: "debian-snapshot"
			url:  "https://snapshot.debian.org/mr/package/python3-defaults/"
		}
		version: "3.11.2-1+b1"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "ripgrep"
		sha256: {
			amd64: "4cf9f2741e6c465ffdb7c26f38056a59e2a2544b51f7cc128ef28337eeae4d8e"
			arm64: "c827481c4ff4ea10c9dc7a4022c8de5db34a5737cb74484d62eb94a95841ab2f"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/BurntSushi/ripgrep/releases/download/{version}/ripgrep-{version}-x86_64-unknown-linux-musl.tar.gz"
				arm64: "https://github.com/BurntSushi/ripgrep/releases/download/{version}/ripgrep-{version}-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/BurntSushi/ripgrep/releases"
		}
		version: "14.1.1"
	}, {
		buildFetch: ["astral.sh", "github.com"]
		kind: "binary"
		name: "ruff"
		sha256: {
			amd64: "ad61c55a3b361e4f451e90247d6ca6018c2563f41c5142c1f8388138bdac96b3"
			arm64: "e4e69fe47ad319aeef0983e26e927907d7521214a7d72c79cf2e2b15316ecfa5"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/astral-sh/ruff/releases/download/{version}/ruff-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/astral-sh/ruff/releases/download/{version}/ruff-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/astral-sh/ruff/releases"
		}
		version: "0.11.0"
	}, {
		buildFetch: ["static.rust-lang.org"]
		kind: "binary"
		name: "rust"
		note: "the rustc+cargo toolchain tarball; cargo fetches crates + the sparse index from *.crates.io and toolchain artifacts from static.rust-lang.org (leading dot covers index/static)"
		runtimeEgress: [".crates.io", "static.rust-lang.org"]
		sha256: {
			amd64: "c295047583a56238ea06b43f849f4b877fa12bfd4c7103f8d9a74c94c9c4e108"
			arm64: "371eadcca97062219cbd8593628eb5d2802bc370515d085fedce1b56b2baed57"
		}
		upstream: {
			asset: {
				amd64: "https://static.rust-lang.org/dist/rust-{version}-x86_64-unknown-linux-gnu.tar.xz"
				arm64: "https://static.rust-lang.org/dist/rust-{version}-aarch64-unknown-linux-gnu.tar.xz"
			}
			kind:        "url-regex"
			manifestURL: "https://static.rust-lang.org/dist/channel-rust-{version}.toml"
			url:         "https://static.rust-lang.org/dist/channel-rust-stable.toml"
		}
		version: "1.96.0"
	}, {
		buildFetch: ["static.rust-lang.org"]
		kind: "binary"
		name: "rustup"
		sha256: {
			amd64: "0000000000000000000000000000000000000000000000000000000000000000"
			arm64: "0000000000000000000000000000000000000000000000000000000000000000"
		}
		upstream: {
			asset: {
				amd64: "https://static.rust-lang.org/rustup/archive/{version}/x86_64-unknown-linux-gnu/rustup-init"
				arm64: "https://static.rust-lang.org/rustup/archive/{version}/aarch64-unknown-linux-gnu/rustup-init"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/rust-lang/rustup/releases"
		}
		version: "1.28.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "sccache"
		sha256: {
			amd64: "1fbb35e135660d04a2d5e42b59c7874d39b3deb17de56330b25b713ec59f849b"
			arm64: "d6a1ce4acd02b937cd61bc675a8be029a60f7bc167594c33d75732bbc0a07400"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/mozilla/sccache/releases/download/v{version}/sccache-v{version}-x86_64-unknown-linux-musl.tar.gz"
				arm64: "https://github.com/mozilla/sccache/releases/download/v{version}/sccache-v{version}-aarch64-unknown-linux-musl.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/mozilla/sccache/releases"
		}
		version: "0.10.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "tokei"
		note: "12.1.2 is the latest stable release with published Linux binary assets; 13.0.0 and 14.0.0 publish source only"
		sha256: {
			amd64: "c8c5c4ab9e1ff47e745de70f4af3214078657399fa7a0da0b5f209d780e49978"
			arm64: "ef514fd12cfc3ee2d1725e5ecb866ee1123163004879ec285b22f3323389ebe2"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/XAMPPRocky/tokei/releases/download/v{version}/tokei-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/XAMPPRocky/tokei/releases/download/v{version}/tokei-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/XAMPPRocky/tokei/releases"
		}
		version: "12.1.2"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "typescript"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/typescript"
		}
		version: "5.8.2"
	}, {
		buildFetch: ["astral.sh", "github.com"]
		kind: "binary"
		name: "uv"
		sha256: {
			amd64: "14411de26cdea5f5139fafaf2b675b1c633e744dd49c6d6a9fc8817ec065158b"
			arm64: "055c329c38a93c01d378349d51cb4d521d1998c8a79355ddc00f863ce451942f"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/astral-sh/uv/releases/download/{version}/uv-x86_64-unknown-linux-gnu.tar.gz"
				arm64: "https://github.com/astral-sh/uv/releases/download/{version}/uv-aarch64-unknown-linux-gnu.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/astral-sh/uv/releases"
		}
		version: "0.5.11"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "vite"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/vite"
		}
		version: "6.3.5"
	}, {
		buildFetch: ["registry.npmjs.org"]
		kind: "npm"
		name: "web-ext"
		requires: ["node"]
		upstream: {
			kind: "npm-registry"
			url:  "https://registry.npmjs.org/web-ext"
		}
		version: "8.5.0"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "yq"
		sha256: {
			amd64: "b96de04645707e14a12f52c37e6266832e03c29e95b9b139cddcae7314466e69"
			arm64: "a02cc637409db44a9f9cb55ea92c40019582ba88083c4d930a727ec4b59ed439"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/mikefarah/yq/releases/download/v{version}/yq_linux_amd64"
				arm64: "https://github.com/mikefarah/yq/releases/download/v{version}/yq_linux_arm64"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/mikefarah/yq/releases"
		}
		version: "4.45.4"
	}, {
		buildFetch: ["github.com"]
		kind: "binary"
		name: "zoxide"
		sha256: {
			amd64: "4092ee38aa1efde42e4efb2f9c872df5388198aacae7f1a74e5eb5c3cc7f531c"
			arm64: "078cc9cc8cedb6c45edb84c0f5bad53518c610859c73bdb3009a52b89652c103"
		}
		upstream: {
			asset: {
				amd64: "https://github.com/ajeetdsouza/zoxide/releases/download/v{version}/zoxide-{version}-x86_64-unknown-linux-musl.tar.gz"
				arm64: "https://github.com/ajeetdsouza/zoxide/releases/download/v{version}/zoxide-{version}-aarch64-unknown-linux-musl.tar.gz"
			}
			kind: "github-releases"
			url:  "https://api.github.com/repos/ajeetdsouza/zoxide/releases"
		}
		version: "0.9.8"
	}]
}
