package policy

import (
	"bytes"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestLoadCatalogFileReadsDiskJSON(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "catalog.json")
	input := []byte(`{
  "packages": [{"name":"tool","kind":"npm","version":"1.0.0"}],
  "bundles": [{"name":"base","description":"base bundle","packages":["tool"]}],
  "defaults": {"claude":"base"}
}
`)
	if err := os.WriteFile(path, input, 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	cat, err := LoadCatalogFile(path)
	if err != nil {
		t.Fatalf("LoadCatalogFile returned error: %v", err)
	}
	if err := cat.Validate(); err != nil {
		t.Fatalf("loaded catalog should validate: %v", err)
	}
	pkg, ok := cat.Lookup("tool")
	if !ok {
		t.Fatal("loaded catalog missing package tool")
	}
	if pkg.Kind != KindNpm || pkg.Version != "1.0.0" {
		t.Fatalf("tool = %#v, want npm 1.0.0", pkg)
	}
	if got := cat.DefaultBundle("claude"); got != "base" {
		t.Fatalf("DefaultBundle(claude) = %q, want base", got)
	}
}

func TestCatalogIOIdempotencyWithRealCatalog(t *testing.T) {
	orig, err := LoadCatalogFile("catalog.json")
	if err != nil {
		t.Fatalf("LoadCatalogFile(real catalog): %v", err)
	}
	if err := orig.Validate(); err != nil {
		t.Fatalf("real catalog should validate: %v", err)
	}
	before := catalogIOSnapshot(orig)

	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, orig); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}
	if after := catalogIOSnapshot(orig); !reflect.DeepEqual(after, before) {
		t.Fatalf("WriteCatalog mutated its input\nbefore=%#v\nafter=%#v", before, after)
	}

	reloaded, err := LoadCatalogFile(tmpJSON)
	if err != nil {
		t.Fatalf("LoadCatalogFile(re-emitted json): %v", err)
	}
	if err := reloaded.Validate(); err != nil {
		t.Fatalf("reloaded catalog should validate: %v", err)
	}
	assertCatalogIOSame(t, reloaded, orig)
	assertCatalogIORenderSync(t, tmpCue, tmpJSON)

	cueBytes, err := os.ReadFile(tmpCue)
	if err != nil {
		t.Fatalf("read emitted cue: %v", err)
	}
	if !bytes.HasPrefix(cueBytes, []byte("package safeslop\n\n// Generated by WriteCatalog; specs/0059 D1")) {
		t.Fatalf("emitted cue missing package/header prefix:\n%s", firstCatalogIOLines(cueBytes, 4))
	}
	if !bytes.Contains(cueBytes, []byte("catalog: {")) {
		t.Fatalf("emitted cue missing top-level catalog field")
	}
}

func TestWriteCatalogMutationRoundTrip(t *testing.T) {
	cat := newCatalog([]Package{
		{
			Name:          "node",
			Kind:          KindBinary,
			Version:       "1.2.3",
			SHA256:        map[string]string{"amd64": catalogIODigest("a"), "arm64": catalogIODigest("b")},
			RuntimeEgress: []string{"nodejs.org"},
		},
	}, []Bundle{{Name: "base", Description: "base bundle", Packages: []string{"node"}}}, map[string]string{"pi": "base"})
	if err := cat.Validate(); err != nil {
		t.Fatalf("synthetic catalog invalid: %v", err)
	}

	withTool, _, err := AddPackage(cat, Package{Name: "tool", Kind: KindNpm, Version: "1.0.0", Requires: []string{"node"}, Note: "added in test"})
	if err != nil {
		t.Fatalf("AddPackage returned error: %v", err)
	}
	wantSHA := map[string]string{"amd64": catalogIODigest("c"), "arm64": catalogIODigest("d")}
	mutated, _, err := BumpPackage(withTool, "node", "1.3.0", wantSHA, "canary")
	if err != nil {
		t.Fatalf("BumpPackage returned error: %v", err)
	}

	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, mutated); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}
	assertCatalogIORenderSync(t, tmpCue, tmpJSON)

	reloaded, err := LoadCatalogFile(tmpJSON)
	if err != nil {
		t.Fatalf("LoadCatalogFile(re-emitted json): %v", err)
	}
	if err := reloaded.Validate(); err != nil {
		t.Fatalf("reloaded catalog should validate: %v", err)
	}
	node, ok := reloaded.Lookup("node")
	if !ok {
		t.Fatal("reloaded catalog missing node")
	}
	if node.Version != "1.3.0" {
		t.Fatalf("node version = %q, want 1.3.0", node.Version)
	}
	if !reflect.DeepEqual(node.SHA256, wantSHA) {
		t.Fatalf("node sha = %v, want %v", node.SHA256, wantSHA)
	}
	tool, ok := reloaded.Lookup("tool")
	if !ok {
		t.Fatal("reloaded catalog missing added tool")
	}
	if tool.Version != "1.0.0" || tool.Note != "added in test" || !reflect.DeepEqual(tool.Requires, []string{"node"}) {
		t.Fatalf("tool = %#v, want version/note/requires persisted", tool)
	}
	if got := reloaded.DefaultBundle("pi"); got != "base" {
		t.Fatalf("DefaultBundle(pi) = %q, want base", got)
	}
}

// TestWriteCatalogPreservesRevisionInt guards the one correctness property that no other
// test exercises: an integer field (Revision) must survive WriteCatalog as CUE `int`, not
// `float`. The schema pins `revision?: int` (schema/catalog.cue), and the tempting route
// the PR text sketches — "marshal structs to JSON, parse into a cue.Value" via a generic
// map[string]any — coerces every number to float64, emitting `revision: 3.0`, which FAILS
// `Validate(cue.Concrete(true))` against the schema. The typed catalogWire route in
// catalog_io.go avoids that, and this test locks it in so a regression to the map route is
// caught here (renderCatalogToJSON would reject the float) rather than in production
// `catalog bump` (the v1.1 same-version byte-rotation path that increments Revision).
// The committed catalog carries no non-zero Revision yet, so without this test the property
// is silently unguarded.
func TestWriteCatalogPreservesRevisionInt(t *testing.T) {
	cat := newCatalog([]Package{
		{Name: "tool", Kind: KindNpm, Version: "1.0.0", Revision: 3},
	}, nil, nil)
	if err := cat.Validate(); err != nil {
		t.Fatalf("synthetic catalog invalid: %v", err)
	}

	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, cat); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}
	// The functional guard: this both renders the cue and Validate(Concrete(true))s it
	// against the schema, so a `revision: 3.0` emission fails here.
	assertCatalogIORenderSync(t, tmpCue, tmpJSON)

	cueBytes, err := os.ReadFile(tmpCue)
	if err != nil {
		t.Fatalf("read emitted cue: %v", err)
	}
	if bytes.Contains(cueBytes, []byte("revision: 3.0")) {
		t.Fatalf("emitted cue rendered Revision as a float (revision: 3.0); must be int:\n%s", cueBytes)
	}
	if !bytes.Contains(cueBytes, []byte("revision: 3")) {
		t.Fatalf("emitted cue missing revision field:\n%s", cueBytes)
	}

	reloaded, err := LoadCatalogFile(tmpJSON)
	if err != nil {
		t.Fatalf("LoadCatalogFile(re-emitted json): %v", err)
	}
	if err := reloaded.Validate(); err != nil {
		t.Fatalf("reloaded catalog should validate: %v", err)
	}
	tool, ok := reloaded.Lookup("tool")
	if !ok {
		t.Fatal("reloaded catalog missing tool")
	}
	if tool.Revision != 3 {
		t.Fatalf("tool.Revision = %d, want 3 (int fidelity lost)", tool.Revision)
	}
}

// TestWriteCatalogPreservesUpstreamAndEgress guards full-fidelity persistence of the
// nested Upstream block (kind/url/asset-map/manifestURL) and RuntimeEgress — the fields
// that dominate the real binary catalog entries and that the CLI mutation path (add /
// bump) must never silently drop when it re-emits both files. It complements the real-
// catalog idempotency test with a small, explicit assertion so a fidelity regression names
// the exact field that broke.
func TestWriteCatalogPreservesUpstreamAndEgress(t *testing.T) {
	up := &Upstream{
		Kind:        "github-releases",
		URL:         "https://api.github.com/repos/x/y/releases",
		Asset:       map[string]string{"amd64": "https://x/y-{version}-amd64.tgz", "arm64": "https://x/y-{version}-arm64.tgz"},
		ManifestURL: "https://x/y-{version}-SHASUMS",
	}
	cat := newCatalog([]Package{
		{
			Name:          "y",
			Kind:          KindBinary,
			Version:       "2.0.0",
			SHA256:        map[string]string{"amd64": catalogIODigest("a"), "arm64": catalogIODigest("b")},
			RuntimeEgress: []string{".example.com", "api.example.org"},
			BuildFetch:    []string{"github.com"},
			Upstream:      up,
			Note:          "pin rationale",
		},
	}, nil, nil)
	if err := cat.Validate(); err != nil {
		t.Fatalf("synthetic catalog invalid: %v", err)
	}

	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, cat); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}
	assertCatalogIORenderSync(t, tmpCue, tmpJSON)

	reloaded, err := LoadCatalogFile(tmpJSON)
	if err != nil {
		t.Fatalf("LoadCatalogFile(re-emitted json): %v", err)
	}
	if err := reloaded.Validate(); err != nil {
		t.Fatalf("reloaded catalog should validate: %v", err)
	}
	y, ok := reloaded.Lookup("y")
	if !ok {
		t.Fatal("reloaded catalog missing y")
	}
	if y.Upstream == nil {
		t.Fatal("reloaded package lost its Upstream block")
	}
	if !reflect.DeepEqual(y.Upstream, up) {
		t.Fatalf("Upstream mismatch\n got=%#v\nwant=%#v", y.Upstream, up)
	}
	if !reflect.DeepEqual(y.RuntimeEgress, []string{".example.com", "api.example.org"}) {
		t.Fatalf("RuntimeEgress mismatch: %#v", y.RuntimeEgress)
	}
	if !reflect.DeepEqual(y.BuildFetch, []string{"github.com"}) {
		t.Fatalf("BuildFetch mismatch: %#v", y.BuildFetch)
	}
	if y.Note != "pin rationale" {
		t.Fatalf("Note not preserved: %q", y.Note)
	}
}

// TestWriteCatalogOmitsEmptyOptionalFields is the regression guard for specs/0059 W6a:
// json omitempty drops empty optional collections, but ctx.Encode emits `[]`/`{}` for a
// non-nil empty slice/map (and an all-empty Upstream), which drifts cue↔json sync after a
// `catalog add` that creates a package with empty optional fields. WriteCatalog must
// normalize those to nil/absent before both emits so the two artifacts stay in lockstep.
func TestWriteCatalogOmitsEmptyOptionalFields(t *testing.T) {
	cat := newCatalog([]Package{
		{
			Name:          "tool",
			Kind:          KindNpm,
			Version:       "1.0.0",
			SHA256:        map[string]string{},
			BuildFetch:    []string{},
			Requires:      []string{},
			RuntimeEgress: []string{},
			Conflicts:     []string{},
			Upstream:      &Upstream{Asset: map[string]string{}},
		},
		{
			Name:    "binary-tool",
			Kind:    KindBinary,
			Version: "1.0.0",
			SHA256:  map[string]string{"amd64": catalogIODigest("a"), "arm64": catalogIODigest("b")},
		},
	}, nil, nil)
	if err := cat.Validate(); err != nil {
		t.Fatalf("synthetic catalog invalid: %v", err)
	}

	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, cat); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}

	cueBytes, err := os.ReadFile(tmpCue)
	if err != nil {
		t.Fatalf("read emitted cue: %v", err)
	}
	for _, bad := range []string{"buildFetch: []", "requires: []", "runtimeEgress: []", "conflicts: []", "sha256: {}", "upstream: {", "null"} {
		if bytes.Contains(cueBytes, []byte(bad)) {
			t.Fatalf("emitted cue contains %q (empty optional not normalized):\n%s", bad, cueBytes)
		}
	}

	// cue↔json sync must hold: render emitted cue equals emitted json byte-for-byte.
	assertCatalogIORenderSync(t, tmpCue, tmpJSON)

	// Reload is idempotent: a second WriteCatalog of the reloaded catalog emits the
	// same bytes for both artifacts.
	reloaded, err := LoadCatalogFile(tmpJSON)
	if err != nil {
		t.Fatalf("LoadCatalogFile(re-emitted json): %v", err)
	}
	if err := reloaded.Validate(); err != nil {
		t.Fatalf("reloaded catalog should validate: %v", err)
	}
	tool, ok := reloaded.Lookup("tool")
	if !ok {
		t.Fatal("reloaded catalog missing tool")
	}
	if tool.Upstream != nil {
		t.Fatalf("empty Upstream survived round-trip: %#v", tool.Upstream)
	}
	if len(tool.SHA256) != 0 {
		t.Fatalf("empty SHA256 map survived round-trip: %#v", tool.SHA256)
	}
	if len(tool.BuildFetch) != 0 || len(tool.Requires) != 0 || len(tool.RuntimeEgress) != 0 || len(tool.Conflicts) != 0 {
		t.Fatalf("empty optional slices survived round-trip: %#v", tool)
	}

	dir2 := t.TempDir()
	tmpCue2 := filepath.Join(dir2, "catalog.cue")
	tmpJSON2 := filepath.Join(dir2, "catalog.json")
	if err := WriteCatalog(tmpCue2, tmpJSON2, reloaded); err != nil {
		t.Fatalf("WriteCatalog(reloaded) returned error: %v", err)
	}
	cueBytes2, err := os.ReadFile(tmpCue2)
	if err != nil {
		t.Fatalf("read re-emitted cue: %v", err)
	}
	if !bytes.Equal(cueBytes, cueBytes2) {
		t.Fatalf("WriteCatalog not idempotent for cue\nfirst:\n%s\nsecond:\n%s", cueBytes, cueBytes2)
	}
	jsonBytes, err := os.ReadFile(tmpJSON)
	if err != nil {
		t.Fatalf("read emitted json: %v", err)
	}
	jsonBytes2, err := os.ReadFile(tmpJSON2)
	if err != nil {
		t.Fatalf("read re-emitted json: %v", err)
	}
	if !bytes.Equal(jsonBytes, jsonBytes2) {
		t.Fatalf("WriteCatalog not idempotent for json\nfirst:\n%s\nsecond:\n%s", jsonBytes, jsonBytes2)
	}
}

// TestWriteCatalogNilCatalogErrors locks the nil-guard error path so a caller mistake is a
// clean error, never a panic writing partial files.
func TestWriteCatalogNilCatalogErrors(t *testing.T) {
	dir := t.TempDir()
	if err := WriteCatalog(filepath.Join(dir, "c.cue"), filepath.Join(dir, "c.json"), nil); err == nil {
		t.Fatal("WriteCatalog(nil) = nil error, want error")
	}
}

// TestWriteCatalogAtomicNoTempResidue proves the atomic write path leaves exactly the two
// artifacts (0644) and no leftover temp files — the backstop for specs/0059 D1's
// never-drift guarantee. A leftover ".catalog.json.tmp-*" would signal a torn write or a
// missing cleanup path.
func TestWriteCatalogAtomicNoTempResidue(t *testing.T) {
	orig, err := LoadCatalogFile("catalog.json")
	if err != nil {
		t.Fatalf("load real catalog: %v", err)
	}
	dir := t.TempDir()
	tmpCue := filepath.Join(dir, "catalog.cue")
	tmpJSON := filepath.Join(dir, "catalog.json")
	if err := WriteCatalog(tmpCue, tmpJSON, orig); err != nil {
		t.Fatalf("WriteCatalog returned error: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read temp dir: %v", err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
		if strings.Contains(e.Name(), ".tmp-") {
			t.Fatalf("leftover temp file after WriteCatalog: %q", e.Name())
		}
	}
	if len(names) != 2 {
		t.Fatalf("WriteCatalog left %v, want exactly catalog.cue + catalog.json", names)
	}
	for _, p := range []string{tmpCue, tmpJSON} {
		info, err := os.Stat(p)
		if err != nil {
			t.Fatalf("stat %s: %v", p, err)
		}
		if info.Mode().Perm() != 0o644 {
			t.Fatalf("%s mode = %v, want 0644", p, info.Mode().Perm())
		}
	}
}

func assertCatalogIORenderSync(t *testing.T, cuePath, jsonPath string) {
	t.Helper()
	cueBytes, err := os.ReadFile(cuePath)
	if err != nil {
		t.Fatalf("read %s: %v", cuePath, err)
	}
	rendered, err := renderCatalogToJSON(cueBytes)
	if err != nil {
		t.Fatalf("render emitted cue: %v", err)
	}
	jsonBytes, err := os.ReadFile(jsonPath)
	if err != nil {
		t.Fatalf("read %s: %v", jsonPath, err)
	}
	if !bytes.Equal(rendered, jsonBytes) {
		t.Fatalf("rendered cue JSON does not match emitted catalog.json\nrendered:\n%s\njson:\n%s", rendered, jsonBytes)
	}
}

func assertCatalogIOSame(t *testing.T, got, want *Catalog) {
	t.Helper()
	gotData := catalogIOSnapshot(got)
	wantData := catalogIOSnapshot(want)
	if !reflect.DeepEqual(gotData, wantData) {
		t.Fatalf("catalog mismatch\ngot=%#v\nwant=%#v", gotData, wantData)
	}
}

func catalogIOSnapshot(c *Catalog) catalogData {
	pkgs := c.Packages()
	for i := range pkgs {
		pkgs[i] = clonePackage(pkgs[i])
	}
	bundles := c.Bundles()
	for i := range bundles {
		bundles[i].Packages = cloneStringSlice(bundles[i].Packages)
	}
	defaults := cloneStringMap(c.defaults)
	if defaults == nil {
		defaults = map[string]string{}
	}
	return catalogData{Packages: pkgs, Bundles: bundles, Defaults: defaults}
}

func catalogIODigest(s string) string { return strings.Repeat(s, 64) }

func firstCatalogIOLines(b []byte, n int) string {
	lines := strings.Split(string(b), "\n")
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
