#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Sync example blocks in fish scripts from README.md sections.

Why this exists:
- README.md is the single source of truth for usage examples.
- Each fish script's --help output should show the same commands so
  contributors do not have to maintain two copies.
- A small marker block in each script gets rewritten in place from the
  named README section. CI uses --check to fail PRs that drift.

Marker syntax in a fish script:

    # BEGIN AUTOGEN: examples section="<exact heading text>"
    echo '  ...autogenerated lines...'
    # END AUTOGEN: examples

The "section" value matches a Markdown heading after stripping leading
'#' characters and whitespace. Within the matched section (until the next
heading of equal or higher level), every fenced ```fish code block is
extracted, and any immediately preceding "1. ...:" or "- ..." line is
emitted as a caption.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

_HEADING_RX = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
_FENCE_OPEN_RX = re.compile(r"^```(\w*)\s*$")
_FENCE_CLOSE = "```"
_BEGIN_RX = re.compile(
    r"^(?P<indent>\s*)#\s*BEGIN AUTOGEN:\s*examples\s+section=\"(?P<section>[^\"]+)\"\s*$"
)
_END_RX = re.compile(r"^(?P<indent>\s*)#\s*END AUTOGEN:\s*examples\s*$")
_CAPTION_RX = re.compile(r"^(\s*)(\d+\.|[-*])\s+(.*?)\s*$")


@dataclass
class Section:
    level: int
    title: str
    body: list[str]


def normalize_title(title: str) -> str:
    """Strip markdown formatting from a heading so callers can address it
    using the rendered (plain-text) form."""
    return title.replace("`", "").strip()


def parse_sections(readme_path: Path) -> dict[str, Section]:
    """Index the README by normalized heading title."""
    sections: dict[str, Section] = {}
    lines = readme_path.read_text().splitlines()

    current: Section | None = None
    for line in lines:
        m = _HEADING_RX.match(line)
        if m:
            level = len(m.group(1))
            title = normalize_title(m.group(2))
            new_section = Section(level=level, title=title, body=[])
            sections[title] = new_section
            current = new_section
            continue
        if current is not None:
            current.body.append(line)
    return sections


def extract_examples(section: Section) -> list[str]:
    """Extract caption + fish code block lines from a section.

    Output is a list of plain-text lines suitable for printing under a
    "Examples:" heading. Captions come from the line immediately preceding
    each fish code block when it looks like a numbered or bulleted step.
    """
    lines = section.body
    out: list[str] = []
    i = 0
    n = len(lines)
    while i < n:
        m = _FENCE_OPEN_RX.match(lines[i])
        if m and m.group(1) == "fish":
            caption = _previous_caption(lines, i)
            if caption is not None:
                if out:
                    out.append("")
                out.append(caption)
            i += 1
            while i < n and lines[i].rstrip() != _FENCE_CLOSE:
                # Indent code block contents under the caption.
                out.append("  " + lines[i])
                i += 1
            i += 1  # skip the closing fence
            continue
        i += 1
    return out


def _previous_caption(lines: list[str], fence_index: int) -> str | None:
    """Return the closest preceding non-empty line if it looks like a step."""
    j = fence_index - 1
    while j >= 0 and not lines[j].strip():
        j -= 1
    if j < 0:
        return None
    candidate = lines[j]
    m = _CAPTION_RX.match(candidate)
    if not m:
        return None
    text = m.group(3).rstrip(":")
    # Strip surrounding markdown emphasis/inline-code formatting that would
    # render as noise in plain --help text.
    text = text.replace("`", "")
    return text + ":"


def fish_quote(s: str) -> str:
    """Quote a string for safe use inside fish single quotes.

    Fish single-quoted strings interpret only \\\\ and \\' escapes; everything
    else is literal. So we escape backslashes first, then single quotes,
    then wrap.
    """
    escaped = s.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def render_block(indent: str, lines: list[str]) -> list[str]:
    """Turn extracted lines into fish source lines under the given indent.

    Blank lines become a bare `echo`. Non-blank lines become
    `echo '<quoted>'`. Caller is responsible for the BEGIN/END markers.
    """
    rendered: list[str] = []
    for line in lines:
        if line == "":
            rendered.append(f"{indent}echo")
        else:
            rendered.append(f"{indent}echo {fish_quote(line)}")
    return rendered


def rewrite_script(
    script_path: Path,
    sections: dict[str, Section],
) -> tuple[bool, list[str]]:
    """Rewrite AUTOGEN blocks in a fish script.

    Returns (changed, problems). `changed` is True if the file content
    differs from the on-disk version. `problems` is a list of human-readable
    issues found (missing section, unclosed marker, etc.) — these always
    fail the run.
    """
    text = script_path.read_text()
    lines = text.splitlines()
    out: list[str] = []
    problems: list[str] = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        bm = _BEGIN_RX.match(line)
        if not bm:
            out.append(line)
            i += 1
            continue

        indent = bm.group("indent")
        title = bm.group("section")
        out.append(line)

        # Find the matching END.
        j = i + 1
        while j < n and not _END_RX.match(lines[j]):
            j += 1
        if j >= n:
            problems.append(
                f"{script_path}: BEGIN AUTOGEN at line {i + 1} has no matching END"
            )
            # Preserve the rest of the file unchanged so the user can fix it.
            out.extend(lines[i + 1 :])
            return (text != "\n".join(out) + ("\n" if text.endswith("\n") else ""), problems)

        # Placeholder sections (e.g. the literal "<exact README heading text>"
        # in scripts/script-template.fish) are intentional — the template is
        # meant to be copied and edited. Skip them silently rather than
        # failing CI.
        if title.startswith("<") and title.endswith(">"):
            out.extend(lines[i + 1 : j + 1])
            i = j + 1
            continue

        section = sections.get(normalize_title(title))
        if section is None:
            problems.append(
                f"{script_path}: section not found in README: \"{title}\""
            )
            # Keep the existing body so we do not silently blank it out.
            out.extend(lines[i + 1 : j + 1])
            i = j + 1
            continue

        examples = extract_examples(section)
        out.extend(render_block(indent, examples))
        out.append(lines[j])  # END marker
        i = j + 1

    new_text = "\n".join(out)
    if text.endswith("\n"):
        new_text += "\n"
    changed = new_text != text
    if changed and not problems:
        script_path_changed = new_text
        # Defer the actual write to the caller so --check can run dry.
        # Stash the new content on the path object via a closure return.
        return (True, [("__write__", new_text)])
    if changed:
        # Even with problems, include the new text so the writer can decide.
        return (True, problems + [("__write__", new_text)])
    return (False, problems)


def find_marked_scripts(scripts_dir: Path) -> list[Path]:
    """Return scripts that contain at least one AUTOGEN BEGIN marker."""
    marked: list[Path] = []
    for path in sorted(scripts_dir.glob("*.fish")):
        try:
            text = path.read_text()
        except OSError:
            continue
        if _BEGIN_RX.search(text) is None and "BEGIN AUTOGEN: examples" not in text:
            continue
        marked.append(path)
    return marked


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("sync", help="Rewrite AUTOGEN blocks in place")
    sub.add_parser("check", help="Exit non-zero if any AUTOGEN block would change")
    parser.add_argument(
        "--repo-root",
        default=None,
        help="Repository root (default: parent of scripts/ inferred from this file)",
    )
    args = parser.parse_args(argv)

    if args.repo_root:
        repo_root = Path(args.repo_root).resolve()
    else:
        repo_root = Path(__file__).resolve().parent.parent.parent

    readme = repo_root / "README.md"
    scripts_dir = repo_root / "scripts"

    if not readme.is_file():
        print(f"README not found: {readme}", file=sys.stderr)
        return 2

    sections = parse_sections(readme)
    marked = find_marked_scripts(scripts_dir)

    any_changed = False
    any_problems = False
    for script in marked:
        changed, problems = rewrite_script(script, sections)
        write_payload = None
        real_problems = []
        for p in problems:
            if isinstance(p, tuple) and p[0] == "__write__":
                write_payload = p[1]
            else:
                real_problems.append(p)
        for p in real_problems:
            print(p, file=sys.stderr)
            any_problems = True
        if changed:
            any_changed = True
            rel = script.relative_to(repo_root)
            if args.cmd == "sync" and write_payload is not None and not real_problems:
                script.write_text(write_payload)
                print(f"updated {rel}")
            elif args.cmd == "check":
                print(f"would update {rel}", file=sys.stderr)

    if any_problems:
        return 2
    if args.cmd == "check" and any_changed:
        print("AUTOGEN drift detected; run scripts/slop-sync-help.fish sync", file=sys.stderr)
        return 1
    if args.cmd == "sync" and not any_changed:
        print("no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
