// Package egress defines the canonical, secret-free proxy policy generation.
package egress

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/freakhill/safeslop/internal/engine/policy"
)

// Destination is one normalized exact FQDN and port in effective proxy order.
type Destination struct {
	Host string
	Port int
}

// Generation binds exact proxy bytes to their durable authority revision.
type Generation struct {
	Revision int
	Hash     string
}

// Build returns the exact proxy overlay and its canonical generation hash.
func Build(destinations []Destination, revision int) (Generation, []byte, error) {
	if revision < 0 {
		return Generation{}, nil, fmt.Errorf("egress revision is invalid")
	}
	for _, destination := range destinations {
		host, port, err := policy.ValidateExactEgress(destination.Host, destination.Port)
		if err != nil || host != destination.Host || port != destination.Port {
			return Generation{}, nil, fmt.Errorf("egress generation contains an invalid exact grant")
		}
	}
	body := []byte(fmt.Sprintf("# safeslop-egress-revision: %d\n%s", revision, Render(destinations)))
	digest := sha256.Sum256(body)
	return Generation{Revision: revision, Hash: hex.EncodeToString(digest[:])}, body, nil
}

// Render emits the reviewed exact Squid ACL include in destination order.
func Render(destinations []Destination) string {
	var body strings.Builder
	if len(destinations) == 0 {
		body.WriteString("# generated by safeslop; no session egress grants (final deny-all remains)\n")
		return body.String()
	}
	for i, destination := range destinations {
		escaped := strings.ReplaceAll(destination.Host, ".", `\.`)
		fmt.Fprintf(&body, "acl grant_%d_host dstdom_regex -n ^%s$\n", i, escaped)
		fmt.Fprintf(&body, "acl grant_%d_port port %d\n", i, destination.Port)
		fmt.Fprintf(&body, "http_access allow grant_%d_host grant_%d_port\n", i, i)
	}
	return body.String()
}
