// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/engine/control/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchEvent_Kind int32

const (
	LaunchEvent_SPAWNED LaunchEvent_Kind = 0
	LaunchEvent_EXITED  LaunchEvent_Kind = 1
	LaunchEvent_ERROR   LaunchEvent_Kind = 2
)

// Enum value maps for LaunchEvent_Kind.
var (
	LaunchEvent_Kind_name = map[int32]string{
		0: "SPAWNED",
		1: "EXITED",
		2: "ERROR",
	}
	LaunchEvent_Kind_value = map[string]int32{
		"SPAWNED": 0,
		"EXITED":  1,
		"ERROR":   2,
	}
)

func (x LaunchEvent_Kind) Enum() *LaunchEvent_Kind {
	p := new(LaunchEvent_Kind)
	*p = x
	return p
}

func (x LaunchEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaunchEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_control_control_proto_enumTypes[0].Descriptor()
}

func (LaunchEvent_Kind) Type() protoreflect.EnumType {
	return &file_internal_engine_control_control_proto_enumTypes[0]
}

func (x LaunchEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LaunchEvent_Kind.Descriptor instead.
func (LaunchEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{6, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListProfilesRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_internal_engine_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Profile) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Profile) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type LaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *LaunchRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *LaunchRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type LaunchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          LaunchEvent_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=slop.control.v1.LaunchEvent_Kind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchEvent) Reset() {
	*x = LaunchEvent{}
	mi := &file_internal_engine_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchEvent) ProtoMessage() {}

func (x *LaunchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchEvent.ProtoReflect.Descriptor instead.
func (*LaunchEvent) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchEvent) GetKind() LaunchEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return LaunchEvent_SPAWNED
}

func (x *LaunchEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LaunchEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_internal_engine_control_control_proto protoreflect.FileDescriptor

const file_internal_engine_control_control_proto_rawDesc = "" +
	"\n" +
	"%internal/engine/control/control.proto\x12\x0fslop.control.v1\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"6\n" +
	"\x13ListProfilesRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"o\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\"L\n" +
	"\x14ListProfilesResponse\x124\n" +
	"\bprofiles\x18\x01 \x03(\v2\x18.slop.control.v1.ProfileR\bprofiles\"J\n" +
	"\rLaunchRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\"\xa7\x01\n" +
	"\vLaunchEvent\x125\n" +
	"\x04kind\x18\x01 \x01(\x0e2!.slop.control.v1.LaunchEvent.KindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"*\n" +
	"\x04Kind\x12\v\n" +
	"\aSPAWNED\x10\x00\x12\n" +
	"\n" +
	"\x06EXITED\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022\xf5\x01\n" +
	"\aControl\x12C\n" +
	"\x04Ping\x12\x1c.slop.control.v1.PingRequest\x1a\x1d.slop.control.v1.PingResponse\x12[\n" +
	"\fListProfiles\x12$.slop.control.v1.ListProfilesRequest\x1a%.slop.control.v1.ListProfilesResponse\x12H\n" +
	"\x06Launch\x12\x1e.slop.control.v1.LaunchRequest\x1a\x1c.slop.control.v1.LaunchEvent0\x01B=Z;github.com/freakhill/safeslop/internal/engine/control/pb;pbb\x06proto3"

var (
	file_internal_engine_control_control_proto_rawDescOnce sync.Once
	file_internal_engine_control_control_proto_rawDescData []byte
)

func file_internal_engine_control_control_proto_rawDescGZIP() []byte {
	file_internal_engine_control_control_proto_rawDescOnce.Do(func() {
		file_internal_engine_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_control_control_proto_rawDesc), len(file_internal_engine_control_control_proto_rawDesc)))
	})
	return file_internal_engine_control_control_proto_rawDescData
}

var file_internal_engine_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_engine_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_engine_control_control_proto_goTypes = []any{
	(LaunchEvent_Kind)(0),        // 0: slop.control.v1.LaunchEvent.Kind
	(*PingRequest)(nil),          // 1: slop.control.v1.PingRequest
	(*PingResponse)(nil),         // 2: slop.control.v1.PingResponse
	(*ListProfilesRequest)(nil),  // 3: slop.control.v1.ListProfilesRequest
	(*Profile)(nil),              // 4: slop.control.v1.Profile
	(*ListProfilesResponse)(nil), // 5: slop.control.v1.ListProfilesResponse
	(*LaunchRequest)(nil),        // 6: slop.control.v1.LaunchRequest
	(*LaunchEvent)(nil),          // 7: slop.control.v1.LaunchEvent
}
var file_internal_engine_control_control_proto_depIdxs = []int32{
	4, // 0: slop.control.v1.ListProfilesResponse.profiles:type_name -> slop.control.v1.Profile
	0, // 1: slop.control.v1.LaunchEvent.kind:type_name -> slop.control.v1.LaunchEvent.Kind
	1, // 2: slop.control.v1.Control.Ping:input_type -> slop.control.v1.PingRequest
	3, // 3: slop.control.v1.Control.ListProfiles:input_type -> slop.control.v1.ListProfilesRequest
	6, // 4: slop.control.v1.Control.Launch:input_type -> slop.control.v1.LaunchRequest
	2, // 5: slop.control.v1.Control.Ping:output_type -> slop.control.v1.PingResponse
	5, // 6: slop.control.v1.Control.ListProfiles:output_type -> slop.control.v1.ListProfilesResponse
	7, // 7: slop.control.v1.Control.Launch:output_type -> slop.control.v1.LaunchEvent
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_engine_control_control_proto_init() }
func file_internal_engine_control_control_proto_init() {
	if File_internal_engine_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_control_control_proto_rawDesc), len(file_internal_engine_control_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_control_control_proto_goTypes,
		DependencyIndexes: file_internal_engine_control_control_proto_depIdxs,
		EnumInfos:         file_internal_engine_control_control_proto_enumTypes,
		MessageInfos:      file_internal_engine_control_control_proto_msgTypes,
	}.Build()
	File_internal_engine_control_control_proto = out.File
	file_internal_engine_control_control_proto_goTypes = nil
	file_internal_engine_control_control_proto_depIdxs = nil
}
