// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/engine/control/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchEvent_Kind int32

const (
	LaunchEvent_SPAWNED LaunchEvent_Kind = 0
	LaunchEvent_EXITED  LaunchEvent_Kind = 1
	LaunchEvent_ERROR   LaunchEvent_Kind = 2
)

// Enum value maps for LaunchEvent_Kind.
var (
	LaunchEvent_Kind_name = map[int32]string{
		0: "SPAWNED",
		1: "EXITED",
		2: "ERROR",
	}
	LaunchEvent_Kind_value = map[string]int32{
		"SPAWNED": 0,
		"EXITED":  1,
		"ERROR":   2,
	}
)

func (x LaunchEvent_Kind) Enum() *LaunchEvent_Kind {
	p := new(LaunchEvent_Kind)
	*p = x
	return p
}

func (x LaunchEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaunchEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_control_control_proto_enumTypes[0].Descriptor()
}

func (LaunchEvent_Kind) Type() protoreflect.EnumType {
	return &file_internal_engine_control_control_proto_enumTypes[0]
}

func (x LaunchEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LaunchEvent_Kind.Descriptor instead.
func (LaunchEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{7, 0}
}

type InstallApplyEvent_Kind int32

const (
	InstallApplyEvent_START    InstallApplyEvent_Kind = 0
	InstallApplyEvent_PROGRESS InstallApplyEvent_Kind = 1
	InstallApplyEvent_DONE     InstallApplyEvent_Kind = 2
	InstallApplyEvent_ERROR    InstallApplyEvent_Kind = 3
)

// Enum value maps for InstallApplyEvent_Kind.
var (
	InstallApplyEvent_Kind_name = map[int32]string{
		0: "START",
		1: "PROGRESS",
		2: "DONE",
		3: "ERROR",
	}
	InstallApplyEvent_Kind_value = map[string]int32{
		"START":    0,
		"PROGRESS": 1,
		"DONE":     2,
		"ERROR":    3,
	}
)

func (x InstallApplyEvent_Kind) Enum() *InstallApplyEvent_Kind {
	p := new(InstallApplyEvent_Kind)
	*p = x
	return p
}

func (x InstallApplyEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallApplyEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_control_control_proto_enumTypes[1].Descriptor()
}

func (InstallApplyEvent_Kind) Type() protoreflect.EnumType {
	return &file_internal_engine_control_control_proto_enumTypes[1]
}

func (x InstallApplyEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallApplyEvent_Kind.Descriptor instead.
func (InstallApplyEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{24, 0}
}

type InstallToolEvent_Kind int32

const (
	InstallToolEvent_LINE  InstallToolEvent_Kind = 0
	InstallToolEvent_DONE  InstallToolEvent_Kind = 1
	InstallToolEvent_ERROR InstallToolEvent_Kind = 2
)

// Enum value maps for InstallToolEvent_Kind.
var (
	InstallToolEvent_Kind_name = map[int32]string{
		0: "LINE",
		1: "DONE",
		2: "ERROR",
	}
	InstallToolEvent_Kind_value = map[string]int32{
		"LINE":  0,
		"DONE":  1,
		"ERROR": 2,
	}
)

func (x InstallToolEvent_Kind) Enum() *InstallToolEvent_Kind {
	p := new(InstallToolEvent_Kind)
	*p = x
	return p
}

func (x InstallToolEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallToolEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_engine_control_control_proto_enumTypes[2].Descriptor()
}

func (InstallToolEvent_Kind) Type() protoreflect.EnumType {
	return &file_internal_engine_control_control_proto_enumTypes[2]
}

func (x InstallToolEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallToolEvent_Kind.Descriptor instead.
func (InstallToolEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{29, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListProfilesRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Tier          string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`                                     // honest isolation tier from policy.EnvTier (e.g. "mistake-guard")
	TierNote      string                 `protobuf:"bytes,6,opt,name=tier_note,json=tierNote,proto3" json:"tier_note,omitempty"`             // the one-line honest caveat from policy.EnvTier
	TrustStatus   string                 `protobuf:"bytes,7,opt,name=trust_status,json=trustStatus,proto3" json:"trust_status,omitempty"`    // per-policy trust gate state: "trusted" | "untrusted" | "changed"
	ConfigDir     string                 `protobuf:"bytes,8,opt,name=config_dir,json=configDir,proto3" json:"config_dir,omitempty"`          // abs dir holding this safeslop.cue (the cockpit runs `safeslop run` here)
	RiskHeadline  string                 `protobuf:"bytes,9,opt,name=risk_headline,json=riskHeadline,proto3" json:"risk_headline,omitempty"` // arbiter one-liner consequence (policy.RiskSummary)
	RiskLevel     string                 `protobuf:"bytes,10,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`         // "high" | "elevated" | "contained" — for color only
	RiskLines     []string               `protobuf:"bytes,11,rep,name=risk_lines,json=riskLines,proto3" json:"risk_lines,omitempty"`         // break-glass consequence sentences
	TechStack     []string               `protobuf:"bytes,12,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`         // underlying technologies (policy.TechStack) — Launch hover tooltip
	RiskAxes      []*RiskAxis            `protobuf:"bytes,13,rep,name=risk_axes,json=riskAxes,proto3" json:"risk_axes,omitempty"`            // per-dimension restriction status — Launch shows the unrestricted ones loud
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_internal_engine_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Profile) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Profile) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Profile) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Profile) GetTierNote() string {
	if x != nil {
		return x.TierNote
	}
	return ""
}

func (x *Profile) GetTrustStatus() string {
	if x != nil {
		return x.TrustStatus
	}
	return ""
}

func (x *Profile) GetConfigDir() string {
	if x != nil {
		return x.ConfigDir
	}
	return ""
}

func (x *Profile) GetRiskHeadline() string {
	if x != nil {
		return x.RiskHeadline
	}
	return ""
}

func (x *Profile) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *Profile) GetRiskLines() []string {
	if x != nil {
		return x.RiskLines
	}
	return nil
}

func (x *Profile) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *Profile) GetRiskAxes() []*RiskAxis {
	if x != nil {
		return x.RiskAxes
	}
	return nil
}

// RiskAxis is one capability dimension's restriction status (policy.RiskAxes). The GUI shows the
// unrestricted ones (restricted=false) as loud amber/red chips — what's OPEN, as prominently as the
// meta line shows what's bounded (ayo S2).
type RiskAxis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`              // "network" | "files"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`            // short status, e.g. "unrestricted", "open egress", "whole account"
	Restricted    bool                   `protobuf:"varint,3,opt,name=restricted,proto3" json:"restricted,omitempty"` // true = bounded; false = unrestricted/open (the loud case)
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`      // "high" | "elevated" | "contained" — color only; value carries the meaning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskAxis) Reset() {
	*x = RiskAxis{}
	mi := &file_internal_engine_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskAxis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskAxis) ProtoMessage() {}

func (x *RiskAxis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskAxis.ProtoReflect.Descriptor instead.
func (*RiskAxis) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *RiskAxis) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskAxis) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RiskAxis) GetRestricted() bool {
	if x != nil {
		return x.Restricted
	}
	return false
}

func (x *RiskAxis) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type LaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *LaunchRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type LaunchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          LaunchEvent_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=safeslop.control.v1.LaunchEvent_Kind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchEvent) Reset() {
	*x = LaunchEvent{}
	mi := &file_internal_engine_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchEvent) ProtoMessage() {}

func (x *LaunchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchEvent.ProtoReflect.Descriptor instead.
func (*LaunchEvent) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchEvent) GetKind() LaunchEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return LaunchEvent_SPAWNED
}

func (x *LaunchEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LaunchEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// OpenSession opens an isolated agent session and allocates its PTY. Non-blocking.
type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *OpenSessionRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *OpenSessionRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *OpenSessionRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *OpenSessionRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{9}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Attach is a long-lived bidi stream: the first ClientFrame carries attach_session_id;
// subsequent client frames are input/resize, server frames are output until exited.
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_internal_engine_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{10}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientFrame_AttachSessionId
	//	*ClientFrame_Input
	//	*ClientFrame_Resize
	Msg           isClientFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_internal_engine_control_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{11}
}

func (x *ClientFrame) GetMsg() isClientFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientFrame) GetAttachSessionId() string {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_AttachSessionId); ok {
			return x.AttachSessionId
		}
	}
	return ""
}

func (x *ClientFrame) GetInput() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientFrame) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isClientFrame_Msg interface {
	isClientFrame_Msg()
}

type ClientFrame_AttachSessionId struct {
	AttachSessionId string `protobuf:"bytes,1,opt,name=attach_session_id,json=attachSessionId,proto3,oneof"` // MUST be the first frame
}

type ClientFrame_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"` // bytes typed into the PTY
}

type ClientFrame_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // terminal resized
}

func (*ClientFrame_AttachSessionId) isClientFrame_Msg() {}

func (*ClientFrame_Input) isClientFrame_Msg() {}

func (*ClientFrame_Resize) isClientFrame_Msg() {}

type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_internal_engine_control_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{12}
}

func (x *Exited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerFrame_Output
	//	*ServerFrame_Exited
	Msg           isServerFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_internal_engine_control_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{13}
}

func (x *ServerFrame) GetMsg() isServerFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerFrame) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ServerFrame_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *ServerFrame) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Msg.(*ServerFrame_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

type isServerFrame_Msg interface {
	isServerFrame_Msg()
}

type ServerFrame_Output struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"` // PTY output bytes
}

type ServerFrame_Exited struct {
	Exited *Exited `protobuf:"bytes,2,opt,name=exited,proto3,oneof"` // agent exited; stream ends after this
}

func (*ServerFrame_Output) isServerFrame_Msg() {}

func (*ServerFrame_Exited) isServerFrame_Msg() {}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{14}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{15}
}

// Trust records host-side approval of a repo's safeslop.cue (its exact bytes), so a
// subsequent OpenSession/Launch for that policy passes the fail-closed trust gate.
// The GUI calls this after the user reviews and approves (specs/0024 S1a follow-on).
type TrustRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustRequest) Reset() {
	*x = TrustRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustRequest) ProtoMessage() {}

func (x *TrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustRequest.ProtoReflect.Descriptor instead.
func (*TrustRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{16}
}

func (x *TrustRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type TrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustedPath   string                 `protobuf:"bytes,1,opt,name=trusted_path,json=trustedPath,proto3" json:"trusted_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustResponse) Reset() {
	*x = TrustResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustResponse) ProtoMessage() {}

func (x *TrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustResponse.ProtoReflect.Descriptor instead.
func (*TrustResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{17}
}

func (x *TrustResponse) GetTrustedPath() string {
	if x != nil {
		return x.TrustedPath
	}
	return ""
}

// Untrust removes a repo's recorded approval (trust.Store.Revoke), so the next list shows it untrusted
// and a launch re-gates through the trust sheet. The reverse of Trust — symmetric revoke (ayo #3). The
// peer is uid/process-tree-checked at Accept, so a sandboxed agent can't revoke (or grant) on its own.
type UntrustRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntrustRequest) Reset() {
	*x = UntrustRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntrustRequest) ProtoMessage() {}

func (x *UntrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntrustRequest.ProtoReflect.Descriptor instead.
func (*UntrustRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{18}
}

func (x *UntrustRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type UntrustResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UntrustedPath string                 `protobuf:"bytes,1,opt,name=untrusted_path,json=untrustedPath,proto3" json:"untrusted_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntrustResponse) Reset() {
	*x = UntrustResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntrustResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntrustResponse) ProtoMessage() {}

func (x *UntrustResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntrustResponse.ProtoReflect.Descriptor instead.
func (*UntrustResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{19}
}

func (x *UntrustResponse) GetUntrustedPath() string {
	if x != nil {
		return x.UntrustedPath
	}
	return ""
}

// InstallPlan returns the pinned desired-state diff (the SP7b-2 plan) for the wizard to preview.
type InstallAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // install | upgrade | ok
	Current       string                 `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	Desired       string                 `protobuf:"bytes,4,opt,name=desired,proto3" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAction) Reset() {
	*x = InstallAction{}
	mi := &file_internal_engine_control_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAction) ProtoMessage() {}

func (x *InstallAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAction.ProtoReflect.Descriptor instead.
func (*InstallAction) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{20}
}

func (x *InstallAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallAction) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InstallAction) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *InstallAction) GetDesired() string {
	if x != nil {
		return x.Desired
	}
	return ""
}

type InstallPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPlanRequest) Reset() {
	*x = InstallPlanRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPlanRequest) ProtoMessage() {}

func (x *InstallPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPlanRequest.ProtoReflect.Descriptor instead.
func (*InstallPlanRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{21}
}

type InstallPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*InstallAction       `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPlanResponse) Reset() {
	*x = InstallPlanResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPlanResponse) ProtoMessage() {}

func (x *InstallPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPlanResponse.ProtoReflect.Descriptor instead.
func (*InstallPlanResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{22}
}

func (x *InstallPlanResponse) GetActions() []*InstallAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// InstallApply streams progress while it downloads, verifies (fail-closed), and installs.
type InstallApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallApplyRequest) Reset() {
	*x = InstallApplyRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallApplyRequest) ProtoMessage() {}

func (x *InstallApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallApplyRequest.ProtoReflect.Descriptor instead.
func (*InstallApplyRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{23}
}

type InstallApplyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          InstallApplyEvent_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=safeslop.control.v1.InstallApplyEvent_Kind" json:"kind,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallApplyEvent) Reset() {
	*x = InstallApplyEvent{}
	mi := &file_internal_engine_control_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallApplyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallApplyEvent) ProtoMessage() {}

func (x *InstallApplyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallApplyEvent.ProtoReflect.Descriptor instead.
func (*InstallApplyEvent) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{24}
}

func (x *InstallApplyEvent) GetKind() InstallApplyEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return InstallApplyEvent_START
}

func (x *InstallApplyEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *InstallApplyEvent) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ListTools returns the Installs-tab catalog with read-only detection of what's already present and
// how it was installed. A present tool is reported with its source and is NOT installable, so safeslop
// never clobbers an existing install (internal/engine/tools).
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogOnly   bool                   `protobuf:"varint,1,opt,name=catalog_only,json=catalogOnly,proto3" json:"catalog_only,omitempty"` // true = instant catalog with detection deferred (Source "unknown")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{25}
}

func (x *ListToolsRequest) GetCatalogOnly() bool {
	if x != nil {
		return x.CatalogOnly
	}
	return false
}

type ToolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Present       bool                   `protobuf:"varint,4,opt,name=present,proto3" json:"present,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // brew | cask | app | standalone | missing
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Installable   bool                   `protobuf:"varint,7,opt,name=installable,proto3" json:"installable,omitempty"`                         // true only when missing AND a route exists (no-clobber)
	InstallHint   string                 `protobuf:"bytes,8,opt,name=install_hint,json=installHint,proto3" json:"install_hint,omitempty"`       // the command that would run, e.g. "brew install uv" (display only)
	ShadowedPaths []string               `protobuf:"bytes,9,rep,name=shadowed_paths,json=shadowedPaths,proto3" json:"shadowed_paths,omitempty"` // other same-name executables later on PATH (shadowed by `path`)
	// The install preview shared by the hover tooltip + consent gate (specs/0037). precautions is set for
	// every tool; the rest are meaningful only when installable.
	Precautions   string `protobuf:"bytes,10,opt,name=precautions,proto3" json:"precautions,omitempty"`                          // what safeslop does to keep this install safe (hover tooltip)
	Verification  string `protobuf:"bytes,11,opt,name=verification,proto3" json:"verification,omitempty"`                        // verified-pin | verified-installer | brew | unverified-run
	SourceUrl     string `protobuf:"bytes,12,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`             // pin download URL (verified-pin/installer only)
	Sha256        string `protobuf:"bytes,13,opt,name=sha256,proto3" json:"sha256,omitempty"`                                    // pinned sha256 (verified-pin/installer only)
	PinnedVersion string `protobuf:"bytes,14,opt,name=pinned_version,json=pinnedVersion,proto3" json:"pinned_version,omitempty"` // pinned version (verified-pin/installer only)
	NeedsConsent  bool   `protobuf:"varint,15,opt,name=needs_consent,json=needsConsent,proto3" json:"needs_consent,omitempty"`   // typed confirmation demanded — unverified script OR unconfined admin installer
	Provenance    string `protobuf:"bytes,16,opt,name=provenance,proto3" json:"provenance,omitempty"`                            // verified-pin/installer only: "vendor" (vendor-published checksum) | "tls" (trust-on-first-use)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStatus) Reset() {
	*x = ToolStatus{}
	mi := &file_internal_engine_control_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus) ProtoMessage() {}

func (x *ToolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus.ProtoReflect.Descriptor instead.
func (*ToolStatus) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{26}
}

func (x *ToolStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolStatus) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ToolStatus) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ToolStatus) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *ToolStatus) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ToolStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ToolStatus) GetInstallable() bool {
	if x != nil {
		return x.Installable
	}
	return false
}

func (x *ToolStatus) GetInstallHint() string {
	if x != nil {
		return x.InstallHint
	}
	return ""
}

func (x *ToolStatus) GetShadowedPaths() []string {
	if x != nil {
		return x.ShadowedPaths
	}
	return nil
}

func (x *ToolStatus) GetPrecautions() string {
	if x != nil {
		return x.Precautions
	}
	return ""
}

func (x *ToolStatus) GetVerification() string {
	if x != nil {
		return x.Verification
	}
	return ""
}

func (x *ToolStatus) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *ToolStatus) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ToolStatus) GetPinnedVersion() string {
	if x != nil {
		return x.PinnedVersion
	}
	return ""
}

func (x *ToolStatus) GetNeedsConsent() bool {
	if x != nil {
		return x.NeedsConsent
	}
	return false
}

func (x *ToolStatus) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolStatus          `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{27}
}

func (x *ListToolsResponse) GetTools() []*ToolStatus {
	if x != nil {
		return x.Tools
	}
	return nil
}

// InstallTool installs ONE missing catalog tool by name, streaming combined output lines. Refuses a
// present tool. People pick tools one at a time — there is no install-everything RPC.
type InstallToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallToolRequest) Reset() {
	*x = InstallToolRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallToolRequest) ProtoMessage() {}

func (x *InstallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallToolRequest.ProtoReflect.Descriptor instead.
func (*InstallToolRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{28}
}

func (x *InstallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InstallToolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          InstallToolEvent_Kind  `protobuf:"varint,1,opt,name=kind,proto3,enum=safeslop.control.v1.InstallToolEvent_Kind" json:"kind,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallToolEvent) Reset() {
	*x = InstallToolEvent{}
	mi := &file_internal_engine_control_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallToolEvent) ProtoMessage() {}

func (x *InstallToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallToolEvent.ProtoReflect.Descriptor instead.
func (*InstallToolEvent) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{29}
}

func (x *InstallToolEvent) GetKind() InstallToolEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return InstallToolEvent_LINE
}

func (x *InstallToolEvent) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// ValidatePolicy vets unsaved safeslop.cue TEXT from the editor (policy.LoadBytes), returning a
// cue-vet-quality error or the parsed profiles each tagged with their tier + arbiter risk summary —
// the live feedback loop for the Create tab. trust_status/config_dir are empty (text isn't on disk).
type ValidatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CueText       string                 `protobuf:"bytes,1,opt,name=cue_text,json=cueText,proto3" json:"cue_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyRequest) Reset() {
	*x = ValidatePolicyRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyRequest) ProtoMessage() {}

func (x *ValidatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyRequest.ProtoReflect.Descriptor instead.
func (*ValidatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{30}
}

func (x *ValidatePolicyRequest) GetCueText() string {
	if x != nil {
		return x.CueText
	}
	return ""
}

type ValidatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty when valid; cue/errors.Details otherwise
	Profiles      []*Profile             `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyResponse) Reset() {
	*x = ValidatePolicyResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyResponse) ProtoMessage() {}

func (x *ValidatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyResponse.ProtoReflect.Descriptor instead.
func (*ValidatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{31}
}

func (x *ValidatePolicyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatePolicyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidatePolicyResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// ListPresets returns the bundled premade policies (the "stdlib") the Create tab offers as starting
// points (policy.Presets). Each is a complete, validated safeslop.cue.
type ListPresetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetsRequest) Reset() {
	*x = ListPresetsRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetsRequest) ProtoMessage() {}

func (x *ListPresetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetsRequest.ProtoReflect.Descriptor instead.
func (*ListPresetsRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{32}
}

type Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // one-line description (not "description" — SwiftProtobuf reserves that)
	Cue           string                 `protobuf:"bytes,3,opt,name=cue,proto3" json:"cue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_internal_engine_control_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{33}
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Preset) GetCue() string {
	if x != nil {
		return x.Cue
	}
	return ""
}

type ListPresetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*Preset              `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetsResponse) Reset() {
	*x = ListPresetsResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetsResponse) ProtoMessage() {}

func (x *ListPresetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetsResponse.ProtoReflect.Descriptor instead.
func (*ListPresetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{34}
}

func (x *ListPresetsResponse) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

// PreflightHostLaunch authors the per-launch host comprehension gate (specs/0030). It is host-tier ONLY
// — calling it for a more-isolated profile is an error — and it is a pure read: nothing is recorded, so
// re-entering the gate re-draws fresh statements (consent is per-launch, never persisted). The engine
// authors every sentence and sets every `expected`, so the affirmed text can't drift from what runs.
type PreflightHostLaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"` // dir holding safeslop.cue; empty = server cwd
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreflightHostLaunchRequest) Reset() {
	*x = PreflightHostLaunchRequest{}
	mi := &file_internal_engine_control_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreflightHostLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreflightHostLaunchRequest) ProtoMessage() {}

func (x *PreflightHostLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreflightHostLaunchRequest.ProtoReflect.Descriptor instead.
func (*PreflightHostLaunchRequest) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{35}
}

func (x *PreflightHostLaunchRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *PreflightHostLaunchRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type ConsentStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Expected      bool                   `protobuf:"varint,2,opt,name=expected,proto3" json:"expected,omitempty"`                      // ground truth: is this statement TRUE of this host run?
	TierOrigin    string                 `protobuf:"bytes,3,opt,name=tier_origin,json=tierOrigin,proto3" json:"tier_origin,omitempty"` // "host" for the true rows; a more-isolated tier for the false decoys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentStatement) Reset() {
	*x = ConsentStatement{}
	mi := &file_internal_engine_control_control_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentStatement) ProtoMessage() {}

func (x *ConsentStatement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentStatement.ProtoReflect.Descriptor instead.
func (*ConsentStatement) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{36}
}

func (x *ConsentStatement) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConsentStatement) GetExpected() bool {
	if x != nil {
		return x.Expected
	}
	return false
}

func (x *ConsentStatement) GetTierOrigin() string {
	if x != nil {
		return x.TierOrigin
	}
	return ""
}

type PreflightHostLaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadlineBody  string                 `protobuf:"bytes,1,opt,name=headline_body,json=headlineBody,proto3" json:"headline_body,omitempty"` // fixed honesty anchor — always true, never answerable
	ScopeLine     string                 `protobuf:"bytes,2,opt,name=scope_line,json=scopeLine,proto3" json:"scope_line,omitempty"`          // per-launch live-state line (varies run to run)
	Statements    []*ConsentStatement    `protobuf:"bytes,3,rep,name=statements,proto3" json:"statements,omitempty"`                         // pre-shuffled rows, guaranteed >=1 true + >=1 false decoy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreflightHostLaunchResponse) Reset() {
	*x = PreflightHostLaunchResponse{}
	mi := &file_internal_engine_control_control_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreflightHostLaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreflightHostLaunchResponse) ProtoMessage() {}

func (x *PreflightHostLaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_engine_control_control_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreflightHostLaunchResponse.ProtoReflect.Descriptor instead.
func (*PreflightHostLaunchResponse) Descriptor() ([]byte, []int) {
	return file_internal_engine_control_control_proto_rawDescGZIP(), []int{37}
}

func (x *PreflightHostLaunchResponse) GetHeadlineBody() string {
	if x != nil {
		return x.HeadlineBody
	}
	return ""
}

func (x *PreflightHostLaunchResponse) GetScopeLine() string {
	if x != nil {
		return x.ScopeLine
	}
	return ""
}

func (x *PreflightHostLaunchResponse) GetStatements() []*ConsentStatement {
	if x != nil {
		return x.Statements
	}
	return nil
}

var File_internal_engine_control_control_proto protoreflect.FileDescriptor

const file_internal_engine_control_control_proto_rawDesc = "" +
	"\n" +
	"%internal/engine/control/control.proto\x12\x13safeslop.control.v1\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"6\n" +
	"\x13ListProfilesRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"\xa0\x03\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12\x1b\n" +
	"\ttier_note\x18\x06 \x01(\tR\btierNote\x12!\n" +
	"\ftrust_status\x18\a \x01(\tR\vtrustStatus\x12\x1d\n" +
	"\n" +
	"config_dir\x18\b \x01(\tR\tconfigDir\x12#\n" +
	"\rrisk_headline\x18\t \x01(\tR\friskHeadline\x12\x1d\n" +
	"\n" +
	"risk_level\x18\n" +
	" \x01(\tR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_lines\x18\v \x03(\tR\triskLines\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\f \x03(\tR\ttechStack\x12:\n" +
	"\trisk_axes\x18\r \x03(\v2\x1d.safeslop.control.v1.RiskAxisR\briskAxes\"p\n" +
	"\bRiskAxis\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"restricted\x18\x03 \x01(\bR\n" +
	"restricted\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\"P\n" +
	"\x14ListProfilesResponse\x128\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1c.safeslop.control.v1.ProfileR\bprofiles\"J\n" +
	"\rLaunchRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\"\xab\x01\n" +
	"\vLaunchEvent\x129\n" +
	"\x04kind\x18\x01 \x01(\x0e2%.safeslop.control.v1.LaunchEvent.KindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"*\n" +
	"\x04Kind\x12\v\n" +
	"\aSPAWNED\x10\x00\x12\n" +
	"\n" +
	"\x06EXITED\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"w\n" +
	"\x12OpenSessionRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"4\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x91\x01\n" +
	"\vClientFrame\x12,\n" +
	"\x11attach_session_id\x18\x01 \x01(\tH\x00R\x0fattachSessionId\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x125\n" +
	"\x06resize\x18\x03 \x01(\v2\x1b.safeslop.control.v1.ResizeH\x00R\x06resizeB\x05\n" +
	"\x03msg\"%\n" +
	"\x06Exited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"e\n" +
	"\vServerFrame\x12\x18\n" +
	"\x06output\x18\x01 \x01(\fH\x00R\x06output\x125\n" +
	"\x06exited\x18\x02 \x01(\v2\x1b.safeslop.control.v1.ExitedH\x00R\x06exitedB\x05\n" +
	"\x03msg\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"/\n" +
	"\fTrustRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"2\n" +
	"\rTrustResponse\x12!\n" +
	"\ftrusted_path\x18\x01 \x01(\tR\vtrustedPath\"1\n" +
	"\x0eUntrustRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"8\n" +
	"\x0fUntrustResponse\x12%\n" +
	"\x0euntrusted_path\x18\x01 \x01(\tR\runtrustedPath\"k\n" +
	"\rInstallAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\tR\acurrent\x12\x18\n" +
	"\adesired\x18\x04 \x01(\tR\adesired\"\x14\n" +
	"\x12InstallPlanRequest\"S\n" +
	"\x13InstallPlanResponse\x12<\n" +
	"\aactions\x18\x01 \x03(\v2\".safeslop.control.v1.InstallActionR\aactions\"\x15\n" +
	"\x13InstallApplyRequest\"\xb0\x01\n" +
	"\x11InstallApplyEvent\x12?\n" +
	"\x04kind\x18\x01 \x01(\x0e2+.safeslop.control.v1.InstallApplyEvent.KindR\x04kind\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"4\n" +
	"\x04Kind\x12\t\n" +
	"\x05START\x10\x00\x12\f\n" +
	"\bPROGRESS\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"5\n" +
	"\x10ListToolsRequest\x12!\n" +
	"\fcatalog_only\x18\x01 \x01(\bR\vcatalogOnly\"\xeb\x03\n" +
	"\n" +
	"ToolStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x18\n" +
	"\apresent\x18\x04 \x01(\bR\apresent\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12 \n" +
	"\vinstallable\x18\a \x01(\bR\vinstallable\x12!\n" +
	"\finstall_hint\x18\b \x01(\tR\vinstallHint\x12%\n" +
	"\x0eshadowed_paths\x18\t \x03(\tR\rshadowedPaths\x12 \n" +
	"\vprecautions\x18\n" +
	" \x01(\tR\vprecautions\x12\"\n" +
	"\fverification\x18\v \x01(\tR\fverification\x12\x1d\n" +
	"\n" +
	"source_url\x18\f \x01(\tR\tsourceUrl\x12\x16\n" +
	"\x06sha256\x18\r \x01(\tR\x06sha256\x12%\n" +
	"\x0epinned_version\x18\x0e \x01(\tR\rpinnedVersion\x12#\n" +
	"\rneeds_consent\x18\x0f \x01(\bR\fneedsConsent\x12\x1e\n" +
	"\n" +
	"provenance\x18\x10 \x01(\tR\n" +
	"provenance\"J\n" +
	"\x11ListToolsResponse\x125\n" +
	"\x05tools\x18\x01 \x03(\v2\x1f.safeslop.control.v1.ToolStatusR\x05tools\"(\n" +
	"\x12InstallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x10InstallToolEvent\x12>\n" +
	"\x04kind\x18\x01 \x01(\x0e2*.safeslop.control.v1.InstallToolEvent.KindR\x04kind\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"%\n" +
	"\x04Kind\x12\b\n" +
	"\x04LINE\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"2\n" +
	"\x15ValidatePolicyRequest\x12\x19\n" +
	"\bcue_text\x18\x01 \x01(\tR\acueText\"~\n" +
	"\x16ValidatePolicyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x128\n" +
	"\bprofiles\x18\x03 \x03(\v2\x1c.safeslop.control.v1.ProfileR\bprofiles\"\x14\n" +
	"\x12ListPresetsRequest\"H\n" +
	"\x06Preset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x10\n" +
	"\x03cue\x18\x03 \x01(\tR\x03cue\"L\n" +
	"\x13ListPresetsResponse\x125\n" +
	"\apresets\x18\x01 \x03(\v2\x1b.safeslop.control.v1.PresetR\apresets\"W\n" +
	"\x1aPreflightHostLaunchRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\"c\n" +
	"\x10ConsentStatement\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\bR\bexpected\x12\x1f\n" +
	"\vtier_origin\x18\x03 \x01(\tR\n" +
	"tierOrigin\"\xa8\x01\n" +
	"\x1bPreflightHostLaunchResponse\x12#\n" +
	"\rheadline_body\x18\x01 \x01(\tR\fheadlineBody\x12\x1d\n" +
	"\n" +
	"scope_line\x18\x02 \x01(\tR\tscopeLine\x12E\n" +
	"\n" +
	"statements\x18\x03 \x03(\v2%.safeslop.control.v1.ConsentStatementR\n" +
	"statements2\x96\v\n" +
	"\aControl\x12K\n" +
	"\x04Ping\x12 .safeslop.control.v1.PingRequest\x1a!.safeslop.control.v1.PingResponse\x12c\n" +
	"\fListProfiles\x12(.safeslop.control.v1.ListProfilesRequest\x1a).safeslop.control.v1.ListProfilesResponse\x12P\n" +
	"\x06Launch\x12\".safeslop.control.v1.LaunchRequest\x1a .safeslop.control.v1.LaunchEvent0\x01\x12`\n" +
	"\vOpenSession\x12'.safeslop.control.v1.OpenSessionRequest\x1a(.safeslop.control.v1.OpenSessionResponse\x12P\n" +
	"\x06Attach\x12 .safeslop.control.v1.ClientFrame\x1a .safeslop.control.v1.ServerFrame(\x010\x01\x12c\n" +
	"\fCloseSession\x12(.safeslop.control.v1.CloseSessionRequest\x1a).safeslop.control.v1.CloseSessionResponse\x12N\n" +
	"\x05Trust\x12!.safeslop.control.v1.TrustRequest\x1a\".safeslop.control.v1.TrustResponse\x12T\n" +
	"\aUntrust\x12#.safeslop.control.v1.UntrustRequest\x1a$.safeslop.control.v1.UntrustResponse\x12`\n" +
	"\vInstallPlan\x12'.safeslop.control.v1.InstallPlanRequest\x1a(.safeslop.control.v1.InstallPlanResponse\x12b\n" +
	"\fInstallApply\x12(.safeslop.control.v1.InstallApplyRequest\x1a&.safeslop.control.v1.InstallApplyEvent0\x01\x12Z\n" +
	"\tListTools\x12%.safeslop.control.v1.ListToolsRequest\x1a&.safeslop.control.v1.ListToolsResponse\x12_\n" +
	"\vInstallTool\x12'.safeslop.control.v1.InstallToolRequest\x1a%.safeslop.control.v1.InstallToolEvent0\x01\x12i\n" +
	"\x0eValidatePolicy\x12*.safeslop.control.v1.ValidatePolicyRequest\x1a+.safeslop.control.v1.ValidatePolicyResponse\x12`\n" +
	"\vListPresets\x12'.safeslop.control.v1.ListPresetsRequest\x1a(.safeslop.control.v1.ListPresetsResponse\x12x\n" +
	"\x13PreflightHostLaunch\x12/.safeslop.control.v1.PreflightHostLaunchRequest\x1a0.safeslop.control.v1.PreflightHostLaunchResponseB=Z;github.com/freakhill/safeslop/internal/engine/control/pb;pbb\x06proto3"

var (
	file_internal_engine_control_control_proto_rawDescOnce sync.Once
	file_internal_engine_control_control_proto_rawDescData []byte
)

func file_internal_engine_control_control_proto_rawDescGZIP() []byte {
	file_internal_engine_control_control_proto_rawDescOnce.Do(func() {
		file_internal_engine_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_engine_control_control_proto_rawDesc), len(file_internal_engine_control_control_proto_rawDesc)))
	})
	return file_internal_engine_control_control_proto_rawDescData
}

var file_internal_engine_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_engine_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_internal_engine_control_control_proto_goTypes = []any{
	(LaunchEvent_Kind)(0),               // 0: safeslop.control.v1.LaunchEvent.Kind
	(InstallApplyEvent_Kind)(0),         // 1: safeslop.control.v1.InstallApplyEvent.Kind
	(InstallToolEvent_Kind)(0),          // 2: safeslop.control.v1.InstallToolEvent.Kind
	(*PingRequest)(nil),                 // 3: safeslop.control.v1.PingRequest
	(*PingResponse)(nil),                // 4: safeslop.control.v1.PingResponse
	(*ListProfilesRequest)(nil),         // 5: safeslop.control.v1.ListProfilesRequest
	(*Profile)(nil),                     // 6: safeslop.control.v1.Profile
	(*RiskAxis)(nil),                    // 7: safeslop.control.v1.RiskAxis
	(*ListProfilesResponse)(nil),        // 8: safeslop.control.v1.ListProfilesResponse
	(*LaunchRequest)(nil),               // 9: safeslop.control.v1.LaunchRequest
	(*LaunchEvent)(nil),                 // 10: safeslop.control.v1.LaunchEvent
	(*OpenSessionRequest)(nil),          // 11: safeslop.control.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),         // 12: safeslop.control.v1.OpenSessionResponse
	(*Resize)(nil),                      // 13: safeslop.control.v1.Resize
	(*ClientFrame)(nil),                 // 14: safeslop.control.v1.ClientFrame
	(*Exited)(nil),                      // 15: safeslop.control.v1.Exited
	(*ServerFrame)(nil),                 // 16: safeslop.control.v1.ServerFrame
	(*CloseSessionRequest)(nil),         // 17: safeslop.control.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),        // 18: safeslop.control.v1.CloseSessionResponse
	(*TrustRequest)(nil),                // 19: safeslop.control.v1.TrustRequest
	(*TrustResponse)(nil),               // 20: safeslop.control.v1.TrustResponse
	(*UntrustRequest)(nil),              // 21: safeslop.control.v1.UntrustRequest
	(*UntrustResponse)(nil),             // 22: safeslop.control.v1.UntrustResponse
	(*InstallAction)(nil),               // 23: safeslop.control.v1.InstallAction
	(*InstallPlanRequest)(nil),          // 24: safeslop.control.v1.InstallPlanRequest
	(*InstallPlanResponse)(nil),         // 25: safeslop.control.v1.InstallPlanResponse
	(*InstallApplyRequest)(nil),         // 26: safeslop.control.v1.InstallApplyRequest
	(*InstallApplyEvent)(nil),           // 27: safeslop.control.v1.InstallApplyEvent
	(*ListToolsRequest)(nil),            // 28: safeslop.control.v1.ListToolsRequest
	(*ToolStatus)(nil),                  // 29: safeslop.control.v1.ToolStatus
	(*ListToolsResponse)(nil),           // 30: safeslop.control.v1.ListToolsResponse
	(*InstallToolRequest)(nil),          // 31: safeslop.control.v1.InstallToolRequest
	(*InstallToolEvent)(nil),            // 32: safeslop.control.v1.InstallToolEvent
	(*ValidatePolicyRequest)(nil),       // 33: safeslop.control.v1.ValidatePolicyRequest
	(*ValidatePolicyResponse)(nil),      // 34: safeslop.control.v1.ValidatePolicyResponse
	(*ListPresetsRequest)(nil),          // 35: safeslop.control.v1.ListPresetsRequest
	(*Preset)(nil),                      // 36: safeslop.control.v1.Preset
	(*ListPresetsResponse)(nil),         // 37: safeslop.control.v1.ListPresetsResponse
	(*PreflightHostLaunchRequest)(nil),  // 38: safeslop.control.v1.PreflightHostLaunchRequest
	(*ConsentStatement)(nil),            // 39: safeslop.control.v1.ConsentStatement
	(*PreflightHostLaunchResponse)(nil), // 40: safeslop.control.v1.PreflightHostLaunchResponse
}
var file_internal_engine_control_control_proto_depIdxs = []int32{
	7,  // 0: safeslop.control.v1.Profile.risk_axes:type_name -> safeslop.control.v1.RiskAxis
	6,  // 1: safeslop.control.v1.ListProfilesResponse.profiles:type_name -> safeslop.control.v1.Profile
	0,  // 2: safeslop.control.v1.LaunchEvent.kind:type_name -> safeslop.control.v1.LaunchEvent.Kind
	13, // 3: safeslop.control.v1.ClientFrame.resize:type_name -> safeslop.control.v1.Resize
	15, // 4: safeslop.control.v1.ServerFrame.exited:type_name -> safeslop.control.v1.Exited
	23, // 5: safeslop.control.v1.InstallPlanResponse.actions:type_name -> safeslop.control.v1.InstallAction
	1,  // 6: safeslop.control.v1.InstallApplyEvent.kind:type_name -> safeslop.control.v1.InstallApplyEvent.Kind
	29, // 7: safeslop.control.v1.ListToolsResponse.tools:type_name -> safeslop.control.v1.ToolStatus
	2,  // 8: safeslop.control.v1.InstallToolEvent.kind:type_name -> safeslop.control.v1.InstallToolEvent.Kind
	6,  // 9: safeslop.control.v1.ValidatePolicyResponse.profiles:type_name -> safeslop.control.v1.Profile
	36, // 10: safeslop.control.v1.ListPresetsResponse.presets:type_name -> safeslop.control.v1.Preset
	39, // 11: safeslop.control.v1.PreflightHostLaunchResponse.statements:type_name -> safeslop.control.v1.ConsentStatement
	3,  // 12: safeslop.control.v1.Control.Ping:input_type -> safeslop.control.v1.PingRequest
	5,  // 13: safeslop.control.v1.Control.ListProfiles:input_type -> safeslop.control.v1.ListProfilesRequest
	9,  // 14: safeslop.control.v1.Control.Launch:input_type -> safeslop.control.v1.LaunchRequest
	11, // 15: safeslop.control.v1.Control.OpenSession:input_type -> safeslop.control.v1.OpenSessionRequest
	14, // 16: safeslop.control.v1.Control.Attach:input_type -> safeslop.control.v1.ClientFrame
	17, // 17: safeslop.control.v1.Control.CloseSession:input_type -> safeslop.control.v1.CloseSessionRequest
	19, // 18: safeslop.control.v1.Control.Trust:input_type -> safeslop.control.v1.TrustRequest
	21, // 19: safeslop.control.v1.Control.Untrust:input_type -> safeslop.control.v1.UntrustRequest
	24, // 20: safeslop.control.v1.Control.InstallPlan:input_type -> safeslop.control.v1.InstallPlanRequest
	26, // 21: safeslop.control.v1.Control.InstallApply:input_type -> safeslop.control.v1.InstallApplyRequest
	28, // 22: safeslop.control.v1.Control.ListTools:input_type -> safeslop.control.v1.ListToolsRequest
	31, // 23: safeslop.control.v1.Control.InstallTool:input_type -> safeslop.control.v1.InstallToolRequest
	33, // 24: safeslop.control.v1.Control.ValidatePolicy:input_type -> safeslop.control.v1.ValidatePolicyRequest
	35, // 25: safeslop.control.v1.Control.ListPresets:input_type -> safeslop.control.v1.ListPresetsRequest
	38, // 26: safeslop.control.v1.Control.PreflightHostLaunch:input_type -> safeslop.control.v1.PreflightHostLaunchRequest
	4,  // 27: safeslop.control.v1.Control.Ping:output_type -> safeslop.control.v1.PingResponse
	8,  // 28: safeslop.control.v1.Control.ListProfiles:output_type -> safeslop.control.v1.ListProfilesResponse
	10, // 29: safeslop.control.v1.Control.Launch:output_type -> safeslop.control.v1.LaunchEvent
	12, // 30: safeslop.control.v1.Control.OpenSession:output_type -> safeslop.control.v1.OpenSessionResponse
	16, // 31: safeslop.control.v1.Control.Attach:output_type -> safeslop.control.v1.ServerFrame
	18, // 32: safeslop.control.v1.Control.CloseSession:output_type -> safeslop.control.v1.CloseSessionResponse
	20, // 33: safeslop.control.v1.Control.Trust:output_type -> safeslop.control.v1.TrustResponse
	22, // 34: safeslop.control.v1.Control.Untrust:output_type -> safeslop.control.v1.UntrustResponse
	25, // 35: safeslop.control.v1.Control.InstallPlan:output_type -> safeslop.control.v1.InstallPlanResponse
	27, // 36: safeslop.control.v1.Control.InstallApply:output_type -> safeslop.control.v1.InstallApplyEvent
	30, // 37: safeslop.control.v1.Control.ListTools:output_type -> safeslop.control.v1.ListToolsResponse
	32, // 38: safeslop.control.v1.Control.InstallTool:output_type -> safeslop.control.v1.InstallToolEvent
	34, // 39: safeslop.control.v1.Control.ValidatePolicy:output_type -> safeslop.control.v1.ValidatePolicyResponse
	37, // 40: safeslop.control.v1.Control.ListPresets:output_type -> safeslop.control.v1.ListPresetsResponse
	40, // 41: safeslop.control.v1.Control.PreflightHostLaunch:output_type -> safeslop.control.v1.PreflightHostLaunchResponse
	27, // [27:42] is the sub-list for method output_type
	12, // [12:27] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_engine_control_control_proto_init() }
func file_internal_engine_control_control_proto_init() {
	if File_internal_engine_control_control_proto != nil {
		return
	}
	file_internal_engine_control_control_proto_msgTypes[11].OneofWrappers = []any{
		(*ClientFrame_AttachSessionId)(nil),
		(*ClientFrame_Input)(nil),
		(*ClientFrame_Resize)(nil),
	}
	file_internal_engine_control_control_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerFrame_Output)(nil),
		(*ServerFrame_Exited)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_engine_control_control_proto_rawDesc), len(file_internal_engine_control_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_engine_control_control_proto_goTypes,
		DependencyIndexes: file_internal_engine_control_control_proto_depIdxs,
		EnumInfos:         file_internal_engine_control_control_proto_enumTypes,
		MessageInfos:      file_internal_engine_control_control_proto_msgTypes,
	}.Build()
	File_internal_engine_control_control_proto = out.File
	file_internal_engine_control_control_proto_goTypes = nil
	file_internal_engine_control_control_proto_depIdxs = nil
}
