#!/usr/bin/env fish

# Unified command hub for this repository's sandbox/key scripts.
# Why: one memorisable entrypoint reduces operator error and shortens onboarding.

set -l script_dir (cd (dirname (status filename)); pwd)

function __sandboxctl_help
    echo "slop-sandboxctl — unified hub for sandbox, VM, and key-lifecycle scripts"
    echo ""
    echo "Description:"
    echo "  One entrypoint that dispatches to every sandbox/VM/key tool in this"
    echo "  repo. Use 'list' to see the mapping, 'tutorial <topic>' for ready-to-"
    echo "  copy quickstarts, or any subcommand below to forward args to the"
    echo "  underlying script. For an interactive launcher, see 'slop'."
    echo ""
    echo "Usage:"
    echo "  scripts/slop-sandboxctl.fish help"
    echo "  scripts/slop-sandboxctl.fish list"
    echo "  scripts/slop-sandboxctl.fish tutorial <topic>"
    echo "  scripts/slop-sandboxctl.fish docker         <args...>   -> slop-agent-sandbox"
    echo "  scripts/slop-sandboxctl.fish docker-tools   <args...>   -> slop-agent-sandbox-tools"
    echo "  scripts/slop-sandboxctl.fish local          <args...>   -> slop-macos-sandbox"
    echo "  scripts/slop-sandboxctl.fish slop-brew-vm        <args...>   -> slop-brew-vm"
    echo "  scripts/slop-sandboxctl.fish github         <args...>   -> slop-gh-key"
    echo "  scripts/slop-sandboxctl.fish forgejo        <args...>   -> slop-forgejo-key"
    echo "  scripts/slop-sandboxctl.fish radicle        <args...>   -> slop-radicle"
    echo "  scripts/slop-sandboxctl.fish safe-npm                   -> slop-safe-npm"
    echo "  scripts/slop-sandboxctl.fish slop-safe-uv        <args...>   -> slop-safe-uv"
    echo "  scripts/slop-sandboxctl.fish pinning                    -> slop-pinning"
    echo "  scripts/slop-sandboxctl.fish isolate        <args...>   -> slop-isolate"
    echo ""
    echo "Topics: docker, local, slop-brew-vm, github-keys, forgejo-keys, radicle-access, network-limiting, file-sharing"
    echo ""
    echo "Examples:"
    echo "  # Discover what each subcommand maps to"
    echo "  scripts/slop-sandboxctl.fish list"
    echo ""
    echo "  # See a focused quickstart for one topic"
    echo "  scripts/slop-sandboxctl.fish tutorial docker"
    echo "  scripts/slop-sandboxctl.fish tutorial github-keys"
    echo ""
    echo "  # Forward args to the underlying tool"
    echo "  scripts/slop-sandboxctl.fish local run --repo-root-access -- /bin/pwd"
    echo "  scripts/slop-sandboxctl.fish github here create-pair       # uses slop-gh-key here"
    echo ""
    echo "Notes:"
    echo "  - For an interactive menu across all of these tools, run: slop"
    echo "  - Per-tool TUIs exist: slop-gh-key tui, slop-forgejo-key tui, slop-radicle tui."
    echo "  - Each subcommand prints its own --help when given no args or --help."
    echo "  - Full reference: README.md."
end

function __sandboxctl_help_to_stderr
    __sandboxctl_help 1>&2
end

function __sandboxctl_list
    echo "Commands:"
    echo "  docker         -> scripts/slop-agent-sandbox.fish (slop-agent-sandbox ...)"
    echo "  docker-tools   -> scripts/slop-agent-sandbox-tools.fish (slop-agent-sandbox-tools ...)"
    echo "  local          -> scripts/slop-macos-sandbox.fish (slop-macos-sandbox ...)"
    echo "  slop-brew-vm        -> scripts/slop-brew-vm.fish (slop-brew-vm ...)"
    echo "  github         -> scripts/slop-gh-key.fish (slop-gh-key ...)"
    echo "  forgejo        -> scripts/slop-forgejo-key.fish (slop-forgejo-key ...)"
    echo "  radicle        -> scripts/slop-radicle.fish (slop-radicle ...)"
    echo "  safe-npm       -> scripts/slop-safe-npm.fish (slop-safe-npm)"
    echo "  slop-safe-uv        -> scripts/slop-safe-uv.fish (slop-safe-uv ...)"
    echo "  pinning        -> scripts/slop-pinning.fish"
    echo "  isolate        -> scripts/slop-isolate.fish (slop-isolate ...)"
end

# Each tutorial topic body is autogenerated from the matching README how-to
# section so the quickstart text and the docs cannot drift. Sections without
# a direct README counterpart (currently: file-sharing) keep hand-written
# bodies and no AUTOGEN block.

function __sandboxctl_tutorial_docker
    echo "Docker sandbox quickstart (from README → 'How to run any agent behind Docker + URL allowlist proxy'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to run any agent behind Docker + URL allowlist proxy"
    echo 'Start the proxy:'
    echo '  docker compose -f library/docker-compose.yml build agent'
    echo '  docker compose -f library/docker-compose.yml up -d proxy'
    echo
    echo 'Run agent container through proxy:'
    echo '  docker compose -f library/docker-compose.yml run --rm agent'
    echo
    echo 'Verify blocking:'
    echo '  docker compose -f library/docker-compose.yml run --rm agent sh -lc \'curl -I https://example.com\''
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_local
    echo "Local macOS sandbox quickstart (from README → 'How to use optional local sandbox-exec layer on macOS'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to use optional local sandbox-exec layer on macOS"
    echo 'Load helper:'
    echo '  source scripts/slop-macos-sandbox.fish'
    echo
    echo 'Run command with default cwd scope and strict egress deny:'
    echo '  slop-macos-sandbox run -- /bin/pwd'
    echo
    echo 'Run command with repository-root scope (alternative to default cwd scope):'
    echo '  slop-macos-sandbox run --repo-root-access -- /usr/bin/env ls'
    echo '  slop-macos-sandbox run --path-scope repo-root -- /usr/bin/env ls'
    echo
    echo 'Use through the unified hub:'
    echo '  scripts/slop-sandboxctl.fish local run --repo-root-access -- /bin/pwd'
    echo
    echo 'Add explicit additional paths only when needed:'
    echo '  slop-macos-sandbox run --allow-read ~/.config --allow-write ./tmp -- /usr/bin/env ls'
    # END AUTOGEN: examples
    echo ""
    echo "Prefer Docker/VM for stronger isolation when executing untrusted workflows."
end

function __sandboxctl_tutorial_brew_vm
    echo "Brew VM quickstart (from README → 'How to sandbox brew with disposable Tart VMs'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to sandbox brew with disposable Tart VMs"
    echo 'Load VM helper:'
    echo '  source scripts/slop-brew-vm.fish'
    echo
    echo 'Create base template once:'
    echo '  slop-brew-vm create-base'
    echo
    echo 'Install formula in disposable VM session:'
    echo '  set -x BREW_VM_PROXY_URL http://<proxy-host>:3128'
    echo '  slop-brew-vm install --network-policy strict-egress <formula>'
    echo
    echo 'Optional: inspect manually in VM shell:'
    echo '  set -x BREW_VM_KEEP_SESSION true'
    echo '  slop-brew-vm install <formula>'
    echo '  slop-brew-vm shell'
    echo '  slop-brew-vm destroy'
    echo
    echo 'Share files explicitly with host:'
    echo '  slop-brew-vm copy-in ./local-file.txt /tmp/llm-share/local-file.txt'
    echo '  slop-brew-vm copy-out /tmp/llm-share/result.txt ./result.txt'
    echo
    echo 'Verify policy enforcement:'
    echo '  slop-brew-vm verify-network'
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_github_keys
    echo "GitHub deploy-key quickstart (from README → 'How to manage ephemeral GitHub SSH deploy keys'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral GitHub SSH deploy keys"
    echo 'Load helper:'
    echo '  source scripts/slop-gh-key.fish'
    echo
    echo 'Create RO + RW key pair for one repo (default TTL 24h):'
    echo '  slop-gh-key create-pair --repo <owner>/<repo> --name session-1 --ttl 24h'
    echo '  slop-gh-key create-pair --repo <owner>/<repo> --name session-1 --ttl 24h --install-ssh-config --host-prefix github-llm'
    echo '  # Read-only: clone, fetch, pull'
    echo '  git clone git@github-llm-ro:<owner>/<repo>.git'
    echo '  git -C <repo> remote set-url origin git@github-llm-ro:<owner>/<repo>.git'
    echo '  '
    echo '  # Read-write: same repo, different alias → gets the RW key'
    echo '  git -C <repo> remote set-url --push origin git@github-llm-rw:<owner>/<repo>.git'
    echo '  git -C <repo> push'
    echo
    echo 'List deploy keys on repo:'
    echo '  slop-gh-key list --repo <owner>/<repo>'
    echo
    echo 'Revoke one key by id:'
    echo '  slop-gh-key revoke --repo <owner>/<repo> --id <key-id>'
    echo
    echo 'Revoke keys by title pattern or expiration:'
    echo '  slop-gh-key revoke-by-title --repo <owner>/<repo> --match \'^llm-agent:\''
    echo '  slop-gh-key revoke-expired --repo <owner>/<repo>'
    echo
    echo 'Generate or install SSH config aliases manually:'
    echo '  slop-gh-key print-ssh-config --ro-key ~/.ssh/llm_agent_github_ro_<stamp> --rw-key ~/.ssh/llm_agent_github_rw_<stamp>'
    echo '  slop-gh-key install-ssh-config --repo <owner>/<repo> --name session-1 --ro-key ~/.ssh/llm_agent_github_ro_<stamp> --rw-key ~/.ssh/llm_agent_github_rw_<stamp>'
    echo
    echo 'Remove old alias blocks from ~/.ssh/config:'
    echo '  slop-gh-key uninstall-ssh-config --repo <owner>/<repo> --name session-1 --yes'
    echo '  slop-gh-key uninstall-ssh-config --marker \'^slop-gh-key:<owner>-<repo>:\' --yes'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: slop-gh-key here create-pair | here list | here revoke <id> | here cleanup | here revoke-all"
end

function __sandboxctl_tutorial_forgejo_keys
    echo "Forgejo deploy-key quickstart (from README → 'How to manage ephemeral Forgejo deploy keys (multi-instance)'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral Forgejo deploy keys (multi-instance)"
    echo 'Load helper:'
    echo '  source scripts/slop-forgejo-key.fish'
    echo '  slop-forgejo-key bootstrap-config'
    echo
    echo 'Save Forgejo instance profile once:'
    echo '  slop-forgejo-key instance-set --name main --url https://forgejo.example.com --token-env FORGEJO_TOKEN_MAIN'
    echo '  set -x FORGEJO_TOKEN_MAIN <token-with-repo-admin>'
    echo
    echo 'Create RO + RW deploy key pair for one repository:'
    echo '  slop-forgejo-key create-pair --instance main --repo <owner>/<repo> --name session-1 --ttl 24h --install-ssh-config'
    echo
    echo 'List and revoke:'
    echo '  slop-forgejo-key list --instance main --repo <owner>/<repo>'
    echo '  slop-forgejo-key revoke --instance main --repo <owner>/<repo> --id <key-id>'
    echo '  slop-forgejo-key revoke-expired --instance main --repo <owner>/<repo> --yes'
    echo
    echo 'Remove old SSH alias blocks:'
    echo '  slop-forgejo-key uninstall-ssh-config --repo <owner>/<repo> --name session-1 --yes'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: slop-forgejo-key here create-pair | here list | here revoke <id> | here cleanup | here revoke-all"
end

function __sandboxctl_tutorial_radicle_access
    echo "Radicle access quickstart (from README → 'How to manage ephemeral Radicle identities across many repos'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to manage ephemeral Radicle identities across many repos"
    echo 'Load helper:'
    echo '  source scripts/slop-radicle.fish'
    echo '  slop-radicle bootstrap-config'
    echo
    echo 'Create short-lived identity:'
    echo '  slop-radicle create-identity --name session-1 --ttl 24h'
    echo
    echo 'Bind identity to current/future repositories by RID:'
    echo '  slop-radicle bind-repo --rid <rad:...> --identity-id <identity-id> --access ro'
    echo '  slop-radicle bind-repo --rid <rad:...> --identity-id <identity-id> --access rw --note "maintainer tasks"'
    echo
    echo 'Inspect and retire:'
    echo '  slop-radicle list-identities'
    echo '  slop-radicle list-bindings --all'
    echo '  slop-radicle retire-expired --yes'
    echo '  slop-radicle unbind-repo --rid <rad:...> --yes'
    echo
    echo 'Print shell export for active identity key:'
    echo '  slop-radicle print-env --identity-id <identity-id>'
    # END AUTOGEN: examples
    echo ""
    echo "Repo-aware shortcuts: slop-radicle here info | here bind --identity-id <id> --access ro|rw | here unbind | here list-bindings"
end

function __sandboxctl_tutorial_network_limiting
    echo "Network limiting quickstart (from README → 'How to strengthen network limiting'):"
    echo ""
    # BEGIN AUTOGEN: examples section="How to strengthen network limiting"
    # END AUTOGEN: examples
end

function __sandboxctl_tutorial_file_sharing
    # No direct README section; this is a synthesis of the slop-brew-vm copy-in/out
    # rules and the docker workspace mount convention.
    echo "File sharing quickstart:"
    echo "  Docker: host repo is /workspace in containers"
    echo "  VM: use explicit transfers only — slop-brew-vm copy-in <host> <guest> / slop-brew-vm copy-out <guest> <host>"
    echo "  Recommended guest share dir: /tmp/llm-share (inside the disposable VM only)"
end

function __sandboxctl_tutorial --argument-names topic
    switch "$topic"
        case docker
            __sandboxctl_tutorial_docker
        case local
            __sandboxctl_tutorial_local
        case slop-brew-vm
            __sandboxctl_tutorial_brew_vm
        case github-keys
            __sandboxctl_tutorial_github_keys
        case forgejo-keys
            __sandboxctl_tutorial_forgejo_keys
        case radicle-access
            __sandboxctl_tutorial_radicle_access
        case network-limiting
            __sandboxctl_tutorial_network_limiting
        case file-sharing
            __sandboxctl_tutorial_file_sharing
        case '*'
            echo "Error: Unknown tutorial topic: $topic" 1>&2
            echo "" 1>&2
            __sandboxctl_help_to_stderr
            return 1
    end
end

if test (count $argv) -eq 0
    __sandboxctl_help
    exit 0
end

set -l cmd "$argv[1]"
set -e argv[1]

switch "$cmd"
    case help --help -h
        __sandboxctl_help
    case list
        __sandboxctl_list
    case tutorial
        if test (count $argv) -ne 1
            echo "Error: 'tutorial' requires exactly one topic." 1>&2
            echo "" 1>&2
            __sandboxctl_help_to_stderr
            exit 1
        end
        __sandboxctl_tutorial "$argv[1]"
    case docker
        fish -c "source '$script_dir/slop-agent-sandbox.fish'; slop-agent-sandbox $argv"
    case docker-tools
        fish -c "source '$script_dir/slop-agent-sandbox-tools.fish'; slop-agent-sandbox-tools $argv"
    case local
        fish -c "source '$script_dir/slop-macos-sandbox.fish'; slop-macos-sandbox $argv"
    case slop-brew-vm
        fish -c "source '$script_dir/slop-brew-vm.fish'; slop-brew-vm $argv"
    case github
        fish -c "source '$script_dir/slop-gh-key.fish'; slop-gh-key $argv"
    case forgejo
        fish -c "source '$script_dir/slop-forgejo-key.fish'; slop-forgejo-key $argv"
    case radicle
        fish -c "source '$script_dir/slop-radicle.fish'; slop-radicle $argv"
    case safe-npm
        fish -c "source '$script_dir/slop-safe-npm.fish'; slop-safe-npm $argv"
    case slop-safe-uv
        fish -c "source '$script_dir/slop-safe-uv.fish'; slop-safe-uv $argv"
    case pinning
        fish "$script_dir/slop-pinning.fish" $argv
    case isolate
        fish -c "source '$script_dir/slop-isolate.fish'; slop-isolate $argv"
    case '*'
        echo "Error: Unknown command: $cmd" 1>&2
        echo "" 1>&2
        __sandboxctl_help_to_stderr
        exit 1
end
