#!/usr/bin/env fish

# Purpose:
# - Install repo fish scripts into the user's fish configuration via a single
#   ~/.config/fish/conf.d/ snippet, so commands are available in every fish
#   session without bin shims or PATH manipulation.
# - Drops the older approach (bin shims + GNU Stow + dispatcher), which had
#   sharp edges around stow tree-folding.
# - Cleans up artifacts of the older install on first run.
#
# Why conf.d:
# - fish's conf.d is auto-sourced on every shell startup; idiomatic for
#   distributing project commands without polluting the user's PATH.
#
# References:
# - fish init: https://fishshell.com/docs/current/language.html#initialization-files

set -g __ift_marker "managed-by: agentic_tactical_boots/slop-install"
set -g __ift_repo_root (cd (dirname (status filename))/..; pwd)
set -g __ift_default_conf_dir "$HOME/.config/fish/conf.d"
set -g __ift_snippet_basename "agentic_tactical_boots.fish"

# Module scripts: define functions with no top-level side-effects, so they
# are safe to source into every fish session at startup.
set -g __ift_module_scripts \
    slop-agent-sandbox \
    slop-agent-sandbox-tools \
    slop-macos-sandbox \
    slop-brew-vm \
    slop-gh-key \
    slop-forgejo-key \
    slop-radicle \
    slop-safe-npm \
    slop-safe-uv \
    slop-isolate

# Standalone scripts: have top-level code that runs immediately, so they
# cannot be sourced. Each gets a thin wrapper function in the snippet.
set -g __ift_standalone_scripts \
    slop-sandboxctl \
    slop \
    slop-pinning \
    slop-sync-help \
    slop-install \
    slop-skills-install

# Legacy paths cleaned up on first run. The first three were created by the
# previous bin-shim/stow installer; the fourth is the bogus tree-fold
# symlink that motivated this rewrite.
set -g __ift_legacy_bin_cmds \
    slop-sandboxctl slop-agent-sandbox slop-agent-sandbox-tools slop-macos-sandbox slop-brew-vm \
    slop-gh-key slop-forgejo-key slop-radicle slop-safe-npm slop-safe-uv \
    slop-pinning slop atb-tui

function __ift_examples
    # BEGIN AUTOGEN: examples section="Install fish command shims"
    echo '  ./install'
    echo '  scripts/slop-install.fish install'
    echo '  scripts/slop-install.fish install --conf-dir /path/to/conf.d'
    echo '  scripts/slop-install.fish status'
    echo '  scripts/slop-install.fish uninstall'
    # END AUTOGEN: examples
end

function __ift_help
    echo "slop-install — install repo fish scripts via ~/.config/fish/conf.d"
    echo ""
    echo "Description:"
    echo "  Generates a fish conf.d snippet that sources every script in this"
    echo "  repo's scripts/ directory into your fish session. Commands like"
    echo "  'slop', 'slop-sandboxctl', and 'slop-gh-key' become available in every"
    echo "  new fish shell with no bin shims and no PATH manipulation. Re-run"
    echo "  any time to refresh the snippet."
    echo ""
    echo "Usage:"
    echo "  scripts/slop-install.fish install [options]"
    echo "  scripts/slop-install.fish uninstall [options]"
    echo "  scripts/slop-install.fish status [--conf-dir <dir>]"
    echo "  scripts/slop-install.fish help"
    echo ""
    echo "Options:"
    echo "  --conf-dir <dir>   Snippet location. Default: $__ift_default_conf_dir"
    echo "  --dry-run          Print what would happen; write nothing."
    echo "  --no-cleanup       Skip removal of legacy ~/.local/bin/ shims and"
    echo "                     associated vendor files from the previous installer."
    echo ""
    echo "Examples (synced from README → 'Install fish command shims'):"
    __ift_examples
    echo ""
    echo "Notes:"
    echo "  - Restart your shell or run 'exec fish' after install to pick up the snippet."
    echo "  - The snippet sources module scripts and wraps standalone ones so they"
    echo "    can be invoked by name from any fish session."
    echo "  - Completions hosted under scripts/completions/ are auto-loaded too."
    echo "  - Legacy bin shims under ~/.local/bin/ are removed unless --no-cleanup."
    echo "  - Full reference: README.md → 'Install fish command shims'."
end

function __ift_help_to_stderr
    __ift_help 1>&2
end

function __ift_snippet_path --argument-names conf_dir
    echo "$conf_dir/$__ift_snippet_basename"
end

# Render the conf.d snippet as a fish-quoted string. The repo root is baked
# in so the snippet is self-contained — moving it to another machine just
# requires re-running install there to update the path.
function __ift_render_snippet
    set -l rr (string escape -- "$__ift_repo_root")

    echo "# $__ift_marker"
    echo "# Auto-generated by scripts/slop-install.fish."
    echo "# Safe to delete or re-run install to regenerate."
    echo ""
    echo "set -gx ATB_REPO_ROOT $rr"
    echo ""
    echo "# Module scripts (define functions, no top-level side effects)."
    echo "for __atb_m in \\"
    set -l n (count $__ift_module_scripts)
    for i in (seq $n)
        set -l name $__ift_module_scripts[$i]
        if test $i -eq $n
            echo "    $name"
        else
            echo "    $name \\"
        end
    end
    echo "    set -l __atb_p \"\$ATB_REPO_ROOT/scripts/\$__atb_m.fish\""
    echo "    if test -f \"\$__atb_p\""
    echo "        source \"\$__atb_p\""
    echo "    end"
    echo "end"
    echo "set -e __atb_m"
    echo ""
    echo "# Wrapper functions for standalone scripts (have top-level code)."
    for s in $__ift_standalone_scripts
        echo "function $s --description '$__ift_marker'"
        echo "    command fish \"\$ATB_REPO_ROOT/scripts/$s.fish\" \$argv"
        echo "end"
    end
    echo ""
    echo "# Completions hosted in the repo."
    echo "for __atb_c in \$ATB_REPO_ROOT/scripts/completions/*.fish"
    echo "    if test -f \"\$__atb_c\""
    echo "        source \"\$__atb_c\""
    echo "    end"
    echo "end"
    echo "set -e __atb_c"
end

# Detect the snippet at the given conf_dir and confirm it is one of ours.
function __ift_is_managed_snippet --argument-names path
    if not test -f "$path"
        return 1
    end
    grep -q "$__ift_marker" "$path"
end

# Cleanup legacy install artifacts. Returns 0 always; prints actions.
function __ift_cleanup_legacy --argument-names target dry_run
    set -l removed 0

    set -l legacy_bin "$target/.local/bin"
    for cmd in $__ift_legacy_bin_cmds
        set -l shim "$legacy_bin/$cmd"
        if test -e "$shim"; or test -L "$shim"
            if test "$dry_run" = "true"
                echo "[dry-run] Would remove legacy bin shim: $shim"
            else
                rm -f "$shim"
                echo "Removed legacy bin shim: $shim"
            end
            set removed (math "$removed + 1")
        end
    end

    set -l legacy_conf "$target/.local/share/fish/vendor_conf.d/agentic_tactical_boots.fish"
    if test -e "$legacy_conf"
        if test "$dry_run" = "true"
            echo "[dry-run] Would remove legacy vendor_conf: $legacy_conf"
        else
            rm -f "$legacy_conf"
            echo "Removed legacy vendor_conf: $legacy_conf"
        end
        set removed (math "$removed + 1")
    end

    set -l legacy_compl_dir "$target/.local/share/fish/vendor_completions.d"
    for cmd in $__ift_legacy_bin_cmds
        set -l f "$legacy_compl_dir/$cmd.fish"
        if test -e "$f"
            if test "$dry_run" = "true"
                echo "[dry-run] Would remove legacy completion: $f"
            else
                rm -f "$f"
                echo "Removed legacy completion: $f"
            end
            set removed (math "$removed + 1")
        end
    end

    # The bogus ~/.local/.local symlink left behind by stow tree-folding
    # against a corrupt source tree. Only remove if it is a symlink (never
    # follow into a real dir, which could be intentional user state).
    set -l bogus "$target/.local/.local"
    if test -L "$bogus"
        if test "$dry_run" = "true"
            echo "[dry-run] Would remove bogus tree-fold symlink: $bogus"
        else
            rm -f "$bogus"
            echo "Removed bogus tree-fold symlink: $bogus"
        end
        set removed (math "$removed + 1")
    end

    # Old installer state file is no longer used; remove it so users do not
    # think there is still something half-installed under ~/.local.
    set -l legacy_state "$target/.config/agentic_tactical_boots/fish-tools.env"
    if test -f "$legacy_state"
        if test "$dry_run" = "true"
            echo "[dry-run] Would remove legacy state file: $legacy_state"
        else
            rm -f "$legacy_state"
            echo "Removed legacy state file: $legacy_state"
        end
        set removed (math "$removed + 1")
    end

    if test $removed -eq 0
        echo "No legacy install artifacts found."
    end
    return 0
end

function __ift_install --argument-names conf_dir dry_run no_cleanup
    set -l snippet (__ift_snippet_path "$conf_dir")
    set -l rendered (__ift_render_snippet)

    if test "$no_cleanup" != "true"
        __ift_cleanup_legacy "$HOME" "$dry_run"
    end

    if test "$dry_run" = "true"
        echo "[dry-run] Would ensure directory: $conf_dir"
        echo "[dry-run] Would write snippet: $snippet"
        echo "[dry-run] Snippet preview:"
        printf '%s\n' $rendered | sed 's/^/    /'
        return 0
    end

    mkdir -p "$conf_dir"; or return 1
    printf '%s\n' $rendered > "$snippet"; or return 1
    chmod 644 "$snippet" 2>/dev/null

    echo "Installed snippet: $snippet"
    echo "Run 'exec fish' or open a new shell to load it."
end

function __ift_uninstall --argument-names conf_dir dry_run
    set -l snippet (__ift_snippet_path "$conf_dir")

    if not test -e "$snippet"
        echo "No snippet found at: $snippet"
        return 0
    end

    if not __ift_is_managed_snippet "$snippet"
        echo "Refusing to remove unmanaged file (no marker): $snippet" 1>&2
        return 1
    end

    if test "$dry_run" = "true"
        echo "[dry-run] Would remove snippet: $snippet"
        return 0
    end

    rm -f "$snippet"; or return 1
    echo "Removed snippet: $snippet"
    echo "Run 'exec fish' or open a new shell so the change takes effect."
end

function __ift_status --argument-names conf_dir
    set -l snippet (__ift_snippet_path "$conf_dir")

    echo "snippet path:      $snippet"
    if test -f "$snippet"
        if __ift_is_managed_snippet "$snippet"
            set -l ts (stat -f '%Sm' -t '%Y-%m-%dT%H:%M:%SZ' "$snippet" 2>/dev/null)
            if test -z "$ts"
                set ts (stat -c '%y' "$snippet" 2>/dev/null)
            end
            echo "snippet status:    installed ($ts)"
        else
            echo "snippet status:    PRESENT BUT NOT MANAGED (no marker)"
        end
    else
        echo "snippet status:    not installed"
    end

    set -l legacy_bin_present 0
    for cmd in $__ift_legacy_bin_cmds
        if test -e "$HOME/.local/bin/$cmd"; or test -L "$HOME/.local/bin/$cmd"
            set legacy_bin_present (math "$legacy_bin_present + 1")
        end
    end
    if test $legacy_bin_present -gt 0
        echo "legacy bin shims:  $legacy_bin_present present (install will clean these up)"
    else
        echo "legacy bin shims:  none"
    end

    if test -L "$HOME/.local/.local"
        echo "tree-fold symlink: PRESENT at ~/.local/.local (install will remove it)"
    end
end

# Entry point.
set -l action ""
set -l conf_dir "$__ift_default_conf_dir"
set -l dry_run "false"
set -l no_cleanup "false"

set -l i 1
while test $i -le (count $argv)
    set -l arg "$argv[$i]"
    switch "$arg"
        case install uninstall status
            set action "$arg"
        case --dry-run
            set dry_run "true"
        case --no-cleanup
            set no_cleanup "true"
        case --conf-dir
            set -l next_i (math "$i + 1")
            if test $next_i -gt (count $argv)
                echo "Error: --conf-dir requires a value" 1>&2
                echo "" 1>&2
                __ift_help_to_stderr
                exit 1
            end
            set conf_dir "$argv[$next_i]"
            set i (math "$i + 1")
        case '--conf-dir=*'
            set conf_dir (string replace -- '--conf-dir=' '' "$arg")
        case help --help -h
            __ift_help
            exit 0
        case '*'
            echo "Error: Unknown argument: $arg" 1>&2
            echo "" 1>&2
            __ift_help_to_stderr
            exit 1
    end
    set i (math "$i + 1")
end

if test -z "$action"
    __ift_help
    exit 0
end

if not string match -q -- '/*' "$conf_dir"
    echo "Error: --conf-dir must be an absolute path (got: $conf_dir)" 1>&2
    echo "" 1>&2
    __ift_help_to_stderr
    exit 1
end

switch "$action"
    case install
        __ift_install "$conf_dir" "$dry_run" "$no_cleanup"
    case uninstall
        __ift_uninstall "$conf_dir" "$dry_run"
    case status
        __ift_status "$conf_dir"
end
