"""Auto-generated by slop-isolate. AG2 executor wired to the unified policy."""

from autogen.coding import DockerCommandLineCodeExecutor

executor = DockerCommandLineCodeExecutor(
    image="local/agent-sandbox:latest",
    work_dir="./tmp",
    timeout=60,
    auto_remove=True,
    stop_container=True,
    extra_volumes=["./", "./tmp"],
    extra_environment={
        "HTTP_PROXY": "http://proxy:3128",
        "HTTPS_PROXY": "http://proxy:3128",
    },
)
